### PR TITLE
[develop] Add smoke and dust verification

### LINKED ISSUE #1219: "Jet" should not have been removed as a valid platform
## Expected behavior
In #1195, tier-1 support for the Jet machine was removed. However, in addition to removing from test files, the value of "JET" was also removed from [`valid_param_vals.yaml`](https://github.com/ufs-community/ufs-srweather-app/blob/develop/ush/valid_param_vals.yaml). This was incorrect, as Jet still functions perfectly for running SRW, it just does not have tier-1 support at this time.

## Current behavior
Can not generate SRW experiments on Jet. As our group in DTC is attempting to run verification experiments on Jet with SRW at this moment, this is unacceptable.

## Machines affected
Jet

## Steps To Reproduce
1. Attempt to generate an experiment on Jet (with config.yaml setting `MACHINE: JET`)
2. Observe error:

```
Traceback (most recent call last):
  File "/mnt/lfs6/BMC/gsd-fv3-dev/Michael.Kavulich/smoke_vx/RRFS_retro/frankenstein_branch/ufs-srweather-app/tests/WE2E/./run_WE2E_tests.py", line 554, in <module>
    run_we2e_tests(homedir,args)
  File "/mnt/lfs6/BMC/gsd-fv3-dev/Michael.Kavulich/smoke_vx/RRFS_retro/frankenstein_branch/ufs-srweather-app/tests/WE2E/./run_WE2E_tests.py", line 230, in run_we2e_tests
    expt_dir = generate_FV3LAM_wflow(ushdir,"config.yaml",logfile=f"{ushdir}/log.generate_FV3LAM_wflow",
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/lfs6/BMC/gsd-fv3-dev/Michael.Kavulich/smoke_vx/RRFS_retro/frankenstein_branch/ufs-srweather-app/tests/WE2E/../../ush/generate_FV3LAM_wflow.py", line 76, in generate_FV3LAM_wflow
    expt_config = setup(ushdir,user_config_fn=config,debug=debug)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/lfs6/BMC/gsd-fv3-dev/Michael.Kavulich/smoke_vx/RRFS_retro/frankenstein_branch/ufs-srweather-app/tests/WE2E/../../ush/setup.py", line 1859, in setup
    raise Exception(
Exception: 
The variable
    MACHINE = JET
in the user's configuration does not have a valid value.  Possible values are:
    MACHINE = ['HERA', 'WCOSS2', 'ORION', 'HERCULES', 'DERECHO', 'LINUX', 'MACOS', 'NOAACLOUD', 'SINGULARITY', 'GAEAC5', 'GAEAC6']
```

## Detailed Description of Fix (optional)
A value of "JET" should be restored to the list on [line 7 of ush/valid_param_vals.yaml](https://github.com/ufs-community/ufs-srweather-app/blob/develop/ush/valid_param_vals.yaml#L7)

## Additional Information (optional)
This is a minor change that shouldn't affect any tests (since EPIC has discontinued regular testing of Jet), so I recommend this change be rolled into an existing PR.

### PR DESCRIPTION
**Pull request by mkavulich**
## DESCRIPTION OF CHANGES: 
This PR adds verification of smoke and dust observations to the SRW verification workflow. These observations come from new data sources: AERONET (aerosol optical depth) and AIRNOW (particulate matter). This necessitated adding some new tasks to the verification section of the workflow, and modifying some existing tasks. A new test, `MET_verification_smoke_only_vx`, has been added to test out these new capabilities. Major updates include:

### New observation types

Two new sets of observations (AERONET and AIRNOW) are now included for ingestion by verification tasks, and all the proper logic has been included for retrieving these obs from HPSS if necessary. In addition, a new capability allows for retrieval of AIRNOW obs from AWS over the internet without needing HPSS access: this can theoretically be extended to other ob types as well but the proper logic will need to be included in `parm/data_locations.yml`

By default, the new observation types also report all matched pairs in the output stat files.

### New MET tool: ASCII2NC
This is a new MET tool for SRW, used for converting the ASCII-based AERONET and AIRNOW obs to NetCDF that can be processed by later MET tasks. This is a new task with a new J-Job and exscript, as well as a new METplus conf file template.

### Generalizing some tasks and metatasks
Some metatasks were previously hard-coded to certain observation types or other variables that needed to become more generic:

 - `metatask_PointStat_SFC_UPA_all_mems` now has an outer loop of metatasks over the observation type, with an inner loop for each ensemble member. This was needed in order to accommodate the new observation types for the PointStat tool.
 - PCP combine is now used for additional functionality that adds two fields in the same forecast file (needed for appropriately creating the PM2.5 variable from forecast output)

### MET and METplus upgrade

These new verification capabilities necessitated an update to a newer MET version, and bugs in 11.1.1 required updating further to MET 12.0.1 and METplus 6.0.0. These have been installed in all the usual places, thanks @RatkoVasic-NOAA!

### Additional updates
In addition, several minor updates are included:
 - Include a fix for MET PCPCombine tasks where files were being over-written for forecasts longer than 24 hours
 - Additional HPSS data location for older NDAS obs
 - By default, verification for gridstat and pointstat is now run on the full domain, not just CONUS
 - Cleaned up the config variable sections imported for some verification tasks; this is part of a pre-resolution of conflicting changes in https://github.com/ufs-community/ufs-srweather-app/pull/1204
 - A bug fix for some functionality in `run_WE2E_tests.py` when parsing an XML with broken/unsatisfied dependencies; now it will properly print an informational message if jobs aren't being submitted properly instead of silently hanging
 - Changed the default of `NUM_MISSING_OBS_FILES_MAX` from 2 to 0; we really shouldn't have missing files for any of our tests, users can bump this up if they need to
 - Replace references to `ln_vrfy` with  `create_symlink_to_file`, and update the latter with wildcard functionality
 - Removed some exported variables from `ush/generate_FV3LAM_wflow.py`, separated out the setting of namelist variables into its own function
 - `ush/retrieve_data.py` now creates directories if they do not exist
 - Move `dict_find()` from `setup.py` to `ush/python_utils/misc.py` for more general use
 - Various typo and formatting fixes
 - Restore "jet" as a valid machine in `ush/valid_param_vals.yaml`

### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
  - See above
- [x] New feature (non-breaking change which adds functionality)
  - See above
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - The `REMOVE_RAW_OBS_*` variables for different observation types are consolidated into a single `REMOVE_RAW_OBS_DIRS` variable
- [x] This change requires a documentation update

## TESTS CONDUCTED: 
- [ ] derecho.intel
- [ ] gaea.intel
- [ ] hera.gnu
- [x] hera.intel
  - Tested all verification tests, as well as fundamental tests
- [ ] hercules.intel
- [x] jet.intel
  - Fundamental tests
- [x] orion.intel
  - Coverage tests
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [x] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## DEPENDENCIES:
None.

## DOCUMENTATION:
Added documentation to the Users Guide for new options where appropriate.

## ISSUE: 
Fixes #1219 

## CHECKLIST
- [x] My code follows the style guidelines in the Contributor's Guide
- [x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

## CONTRIBUTORS (optional): 
Thanks to @RatkoVasic-NOAA, @ulmononian, @christinaholtNOAA, and @gsketefian for their help and contributions

### CODE REVIEW

**Comment by mkavulich** [comment]
I'm opening this PR for review! There are a few failing tests but I believe that just requires updates to the test files; I will work on this tomorrow. All WE2E tests are passing.

File: modulefiles/build_hera_gnu.lua [hunk 1]
```diff
@@ -7,10 +7,10 @@ whatis([===[Loads libraries needed for building the UFS SRW App on Hera using GN
 
 prepend_path("MODULEPATH", "/scratch2/NCEPDEV/stmp1/role.epic/installs/gnu/modulefiles")
 prepend_path("MODULEPATH", "/scratch2/NCEPDEV/stmp1/role.epic/installs/openmpi/modulefiles")
-prepend_path("MODULEPATH", "/scratch2/NCEPDEV/stmp1/role.epic/spack-stack/spack-stack-1.6.0_gnu13/envs/fms-2024.01/install/modulefiles/Core")
+prepend_path("MODULEPATH", "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/test.remove/install/modulefiles/Core")
 
-load("stack-gcc/13.3.0")
-load("stack-openmpi/4.1.6")
+load("stack-gcc/9.2.0")
```
Comment (natalie-perlin) [inline modulefiles/build_hera_gnu.lua]: Is there a reason the gnu stack was downgraded to use gcc/9.2.0 and stack-openmpi/4.1.5?..

Comment (ulmononian) [reply modulefiles/build_hera_gnu.lua]: @mkavulich i assume this change was just for your testing? i believe it should indeed point to `/scratch2/NCEPDEV/stmp1/role.epic/spack-stack/spack-stack-1.6.0_gnu13/envs/fms-2024.01/install/modulefiles/Core` for the gnu stack that contains the new met/metplus versions. is this correct, @RatkoVasic-NOAA?

Comment (mkavulich) [reply modulefiles/build_hera_gnu.lua]: Thanks for pointing this out, this was leftover from some early testing months ago. I am surprised this didn't throw a conflict when I merged the latest `develop`

**Comment by mkavulich** [comment]
I have fixed the failing unit tests...I forgot that templates can be passed to retrieve_data.py, so the literal output_path didn't exist. I changed this script to just make the directories; it's silly that we don't just create a directory that the user has specified if they have permission to do so.

**Comment by mkavulich** [comment]
Okay, so one of the tests is still failing. @MichaelLueken I will need some help on this, because I can not replicate this unit test failure on Hera.

**Comment by MichaelLueken** [comment]
@mkavulich -

I see the following fatal error in the GHA unit tests for `test_generate_FV3LAM_wflow`:
```
FATAL ERROR: 
Cannot create symlink to specified target file because the latter does
not exist or is not a file:
    target = '/home/username/DATA/UFS/fix/fix_am'
Exiting with nonzero status.
```
The issue appears to be symlinking fixed files that aren't staged in the GitHub runner.  This would also show why the test would successfully run on a Tier-1 platform (all necessary staged files are available).

**Comment by mkavulich** [comment]
@MichaelLueken Is there some way to get more information about this error? I can't tell from the output what line is failing, what the input is, etc. It's very hard for me to determine the problem without this information, especially because I haven't changed anything related to fix files in this PR.

**Comment by MichaelLueken** [comment]
@mkavulich -

Here is the full log of the failed test:
```
Read initial values from /home/runner/work/ufs-srweather-app/expt_dirs/test_community/rocoto_defns.yaml
  Creating symlink in the experiment directory (EXPTDIR) that points to the
  workflow launch script (WFLOW_LAUNCH_SCRIPT_FP):
    EXPTDIR = '/home/runner/work/ufs-srweather-app/expt_dirs/test_community'
    WFLOW_LAUNCH_SCRIPT_FP = '/home/runner/work/ufs-srweather-app/ufs-srweather-app/tests/test_python/../../ush/launch_FV3LAM_wflow.sh'
  Symlinking fixed files from system directory (FIXgsm) to a subdirectory (FIXam):
    FIXgsm = '/home/username/DATA/UFS/fix/fix_am'
    FIXam = '/home/runner/work/ufs-srweather-app/expt_dirs/test_community/fix_am'
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/unittest/main.py", line 105, in __init__
    self.runTests()
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/unittest/main.py", line 281, in runTests
    self.result = testRunner.run(self.test)
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/unittest/runner.py", line 240, in run
    test(result)
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/unittest/suite.py", line 122, in run
    test(result)
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/unittest/suite.py", line 122, in run
    test(result)
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/unittest/suite.py", line 122, in run
    test(result)
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/unittest/case.py", line 690, in __call__
    return self.run(*args, **kwds)
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
  File "/home/runner/work/ufs-srweather-app/ufs-srweather-app/tests/test_python/test_generate_FV3LAM_wflow.py", line 56, in test_generate_FV3LAM_wflow
    run_workflow(USHdir, logfile)
  File "/home/runner/work/ufs-srweather-app/ufs-srweather-app/tests/test_python/test_generate_FV3LAM_wflow.py", line 31, in run_workflow
    p.start()
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    return Popen(process_obj)
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/runner/micromamba/envs/srw_app/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/work/ufs-srweather-app/ufs-srweather-app/ush/generate_FV3LAM_wflow.py", line 191, in generate_FV3LAM_wflow
    create_symlink_to_file(fixgsm,fixam,False)
  File "/home/runner/work/ufs-srweather-app/ufs-srweather-app/ush/python_utils/create_symlink_to_file.py", line 45, in create_symlink_to_file
    print_err_msg_exit(
  File "/home/runner/work/ufs-srweather-app/ufs-srweather-app/ush/python_utils/print_msg.py", line 18, in print_err_msg_exit
    traceback.print_stack(file=sys.stderr)
FATAL ERROR: 
Cannot create symlink to specified target file because the latter does
not exist or is not a file:
    target = '/home/username/DATA/UFS/fix/fix_am'
Exiting with nonzero status.
```

**Comment by mkavulich** [comment]
@MichaelLueken From what I can tell this is a problem with the test, not my changes. My changes include logic to ensure that symlinks that are created via `generate_FV3LAM_wflow.py` are not broken, and on the test platform they are broken because this fix file directory does not exist, which is causing a failure.

I don't know what to do about this. Possible solutions to this are to have this test retrieve data from the web so that these checks will pass, or create "dummy" directories in the test file. I'd rather not remove this new error check because the testing is insufficient, and including a flag to turn off this check just for this test seems kludgy. When I attempt to manually create directories on the GitHub runner as part of the tests, I get `PermissionError: [Errno 13] Permission denied: '/home/username'`, so that doesn't seem to be an option unless some kind of settings are changed.

**Comment by mkavulich** [comment]
@MichaelLueken I could also pull this `create_symlink_to_file` change out into its own PR; I'd really like to include it but I don't want that to be the thing holding up reviews of this PR.

**Comment by MichaelLueken** [comment]
@mkavulich -

Yeah, in improving the symlinking in `generate_FV3LAM_wflow`, I suspect that is the cause of this specific failure now.

EPIC does have the fix files in a S3 bucket - https://noaa-ufs-srw-pds.s3.amazonaws.com/index.html#develop-20240618/fix/.

It would be interesting to see if pulling from the S3 bucket and updating the `FIXgsm` path in `ush/machine/linux.yaml` to point to the retrieved fixed files will allow the `test_generate_FV3LAM_wflow` test to successfully run.

**Comment by MichaelLueken** [comment]
@mkavulich -

I would recommend attempting to pull the fixed files from the S3 bucket and seeing if the tests will pass using the pulled files.  If everything works as expected, then we can move forward.  Should the tests continue to fail even with the retrieved fixed files, then the `create_symlink_to_file` update will need to be pulled, since this PR is one of the required PRs to enter code slush.

**Comment by mkavulich** [comment]
@MichaelLueken I wasn't able to retrieve the fix file data because there wasn't enough disk space on the standard GitHub runner. I was able to get the tests to pass by creating "dummy" directories on the runner and modifying the machine file to point to those. See the changes to the first two files here: https://github.com/ufs-community/ufs-srweather-app/pull/1174/files/d30a8ce5364c98ae9dbbbf0e8939d16c35f567a4..644dbda46e4407ee959d1e9105b01847013b1a0b

File: modulefiles/tasks/gaeac6/run_vx.local.lua
Comment (MichaelLueken) [inline modulefiles/tasks/gaeac6/run_vx.local.lua:1]: The update to `run_vx.local.lua` should also be made to `gaeac5`.

File: ush/machine/gaeac5.yaml
Comment (MichaelLueken) [inline ush/machine/gaeac5.yaml:1]: The modifications made to `WE2E_TEST_DATA`, `TEST_CCPA_OBS_DIR`, `TEST_MRMS_OBS_DIR`, `TEST_NDAS_OBS_DIR`, `TEST_NOHRSC_OBS_DIR`, `TEST_AERONET_OBS_DIR`, `TEST_AIRNOW_OBS_DIR`, and `DOMAIN_PREGEN_BASEDIR` should be made to `ush/machine/gaeac6.yaml` as well.

**Review by MichaelLueken — CHANGES_REQUESTED** [review]
@mkavulich -

Excellent job on finding a fix for the generate_FV3LAM_wflow unit test!

I only have two minor issues:
1. The changes in `run_vx.local.lua` should also be applied to `modulefiles/tasks/gaeac5`.
2. The changes in the machine files should also be applied to `ush/machine/gaeac6.yaml`.

I was able to successfully run the new `MET_verification_smoke_only_vx` WE2E test on Hercules:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
MET_verification_smoke_only_vx_20250224104122                      COMPLETE               0.52
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE               0.52
```
Will approve once `modulefiles/tasks/gaeac5/run_vx.local.lua` and `ush/machine/gaeac6.yaml` have been updated.

File: ush/machine/gaeac5.yaml
Comment (mkavulich) [reply ush/machine/gaeac5.yaml:1]: Done!

File: modulefiles/tasks/gaeac6/run_vx.local.lua
Comment (mkavulich) [reply modulefiles/tasks/gaeac6/run_vx.local.lua:1]: Done!

**Review by MichaelLueken — APPROVED** [review]
Thanks, @mkavulich!

File: doc/UsersGuide/BuildingRunningTesting/RunSRW.rst [hunk 2]
```diff
@@ -846,14 +858,18 @@ place them in the locations specified by ``{*_OBS_DIR}/{OBS_*_FN_TEMPLATES[1,3,.
...
-     from collections of publicly available data. 
+     need to download :term:`CCPA`, :term:`NOHRSC`, :term:`MRMS`, :term:`NDAS`, :term:`AERONET`, and/or
+     :term:`AIRNOW` files manually from collections of publicly available data.
      Then, as above, they must set ``*_OBS_DIR`` and ``OBS_*_FN_TEMPLATES[1,3,...]`` to match those
      staging locations and file names.
-   
+
+.. note::
+   AIRNOW observations can be retrieved from AWS in addition to HPSS, but this requires changing some default settings.
+   See ``ush/config_defaults.yaml`` or :numref:`Section %s <GeneralVXParams>` for more details.
```
Comment (christinaholtNOAA) [inline doc/UsersGuide/BuildingRunningTesting/RunSRW.rst]:
```suggestion
   AIRNOW observations can be retrieved from AWS or HPSS, but retrieving from AWS requires changing some default settings.
   See ``ush/config_defaults.yaml`` or :numref:`Section %s <GeneralVXParams>` for more details. 
```

File: doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst [hunk 3]
```diff
@@ -633,7 +633,7 @@ Pre-Existing Directory Parameter
 
    * **"delete":** The preexisting directory is deleted and a new directory (having the same name as the original preexisting directory) is created.
 
-   * **"rename":** The preexisting directory is renamed and a new directory (having the same name as the original pre-existing directory) is created. The new name of the preexisting directory consists of its original name and the suffix "_old###", where ``###`` is a 3-digit integer chosen to make the new name unique.
+   * **"rename":** The preexisting directory is renamed and a new directory (having the same name as the original pre-existing directory) is created. The new name of the preexisting directory consists of its original name and the suffix "_old_YYYYMMDD_HHmmss", where ``YYYYMMDD_HHmmss`` is the full date and time of the rename
```
Comment (christinaholtNOAA) [inline doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst:636]: This line seems incomplete.

File: doc/UsersGuide/Reference/Glossary.rst [hunk 4]
```diff
@@ -12,6 +12,12 @@ Glossary
    advection
       According to the American Meteorological Society (AMS) definition, `advection <https://glossary.ametsoc.org/wiki/Advection>`_ is "The process of transport of an atmospheric property solely by the mass motion (velocity field) of the atmosphere." In common parlance, advection is movement of atmospheric substances that are carried around by the wind.
 
+   AERONET
+      The "`AErosol RObotic NETwork <https://aeronet.gsfc.nasa.gov/>`_": A worldwide ground-based remote sensing aerosol networks established by NASA and PHOTONS. The SRW verification tasks can use "Level 1.5" (cloud-screened and quality-controlled) aerosol optical depth observations.
```
Comment (christinaholtNOAA) [inline doc/UsersGuide/Reference/Glossary.rst]:
```suggestion
      The "`AErosol RObotic NETwork <https://aeronet.gsfc.nasa.gov/>`_": A worldwide ground-based remote sensing aerosol network established by NASA and PHOTONS. The SRW verification tasks can use "Level 1.5" (cloud-screened and quality-controlled) aerosol optical depth observations. 
```

File: doc/UsersGuide/Reference/Glossary.rst [hunk 5]
```diff
@@ -12,6 +12,12 @@ Glossary
    advection
       According to the American Meteorological Society (AMS) definition, `advection <https://glossary.ametsoc.org/wiki/Advection>`_ is "The process of transport of an atmospheric property solely by the mass motion (velocity field) of the atmosphere." In common parlance, advection is movement of atmospheric substances that are carried around by the wind.
 
+   AERONET
+      The "`AErosol RObotic NETwork <https://aeronet.gsfc.nasa.gov/>`_": A worldwide ground-based remote sensing aerosol networks established by NASA and PHOTONS. The SRW verification tasks can use "Level 1.5" (cloud-screened and quality-controlled) aerosol optical depth observations. 
+
+   AIRNOW
+      A North American ground-level air quality measurement network. The SRW verification tasks can use PM2.5 and PM10 observations. More information available at https://www.airnow.gov/
```
Comment (christinaholtNOAA) [inline doc/UsersGuide/Reference/Glossary.rst:19]: Should this be a hyperlink?

File: doc/UsersGuide/Reference/Glossary.rst [hunk 6]
```diff
@@ -159,7 +165,8 @@ Glossary
...
 
    MET
-      The `Model Evaluation Tools <https://dtcenter.org/community-code/model-evaluation-tools-met>`__ is a highly-configurable, state-of-the-art suite of verification tools developed at the :term:`DTC`.
+   METplus
+      The `Model Evaluation Tools <https://dtcenter.org/community-code/model-evaluation-tools-met>`__ is a highly-configurable, state-of-the-art suite of verification tools developed at the :term:`DTC`. `METplus <https://dtcenter.org/community-code/metplus>`_ is a suite of python wrappers providing low-level automation of the MET tools.
```
Comment (christinaholtNOAA) [inline doc/UsersGuide/Reference/Glossary.rst]:
```suggestion
      The `Model Evaluation Tools <https://dtcenter.org/community-code/model-evaluation-tools-met>`__ is a highly configurable, state-of-the-art suite of verification tools developed at the :term:`DTC`. `METplus <https://dtcenter.org/community-code/metplus>`_ is a suite of Python wrappers providing low-level automation of the MET tools.
```

File: jobs/JREGIONAL_RUN_MET_ASCII2NC_OBS [hunk 7]
```diff
@@ -0,0 +1,84 @@
+#!/usr/bin/env bash
+
+#
```
Comment (christinaholtNOAA) [inline jobs/JREGIONAL_RUN_MET_ASCII2NC_OBS:3]: It could be nice to have a doc block with a description of what this job does.

File: parm/wflow/verify_det.yaml [hunk 8]
```diff
@@ -136,49 +136,60 @@ metatask_GridStat_REFC_RETOP_all_mems:
               age: 00:00:00:30
             text: !cycstr '{{ workflow.EXPTDIR }}/@Y@m@d@H/post_files_exist_mem#mem#.txt'
 
-metatask_PointStat_SFC_UPA_all_mems:
+metatask_PointStat:
   var:
-    mem: '{% if global.DO_ENSEMBLE %}{% for m in range(1, global.NUM_ENS_MEMBERS+1) %}{{ "%03d "%m }}{%- endfor -%} {% else %}{{ "000"|string }}{% endif %}'
-  metatask_PointStat_SFC_UPA_mem#mem#:
+    FIELD_GROUP: '{% for var in verification.VX_FIELD_GROUPS %}{% if var in ["SFC", "UPA", "AOD", "PM25", "PM10"] %}{{ "%s " % var }}{% endif %}{% endfor %}'
```
Comment (christinaholtNOAA) [inline parm/wflow/verify_det.yaml:141]: It's cleaner and easier to read to use the one-liner Jinja if-statement in cases like these (and in the next lines):

```
{{ "%s " % var if var in ["SFC", "UPA", "AOD", "PM25", "PM10"] }}
```

There aren't as many `{% %}` blocks to keep up with.

File: parm/wflow/verify_det.yaml [hunk 9]
```diff
@@ -136,49 +136,60 @@ metatask_GridStat_REFC_RETOP_all_mems:
...
+    METAOBTYPE: '{% for var in verification.VX_FIELD_GROUPS %}{% if var =="SFC" or var =="UPA" %}NDAS {% elif var =="AOD" %}AERONET {% elif var =="PM25" or var =="PM10" %}AIRNOW {% endif %}{% endfor %}'
+    METAOBS_DIR: '{% for var in verification.VX_FIELD_GROUPS %}{% if var =="SFC" or var =="UPA" %}&NDAS_OBS_DIR; {% elif var =="AOD" %}&AERONET_OBS_DIR; {% elif var =="PM25" or var =="PM10" %}&AIRNOW_OBS_DIR; {% endif %}{% endfor %}'
+    METAOB_AVAIL_HRS: '{% for var in verification.VX_FIELD_GROUPS %}{% if var =="SFC" or var =="UPA" %} {{- verification.NDAS_OBS_AVAIL_INTVL_HRS }} {% elif var =="AOD" %}{{- verification.AERONET_OBS_AVAIL_INTVL_HRS }} {% elif var =="PM25" or var =="PM10" %}{{- verification.AIRNOW_OBS_AVAIL_INTVL_HRS }} {% endif %}{% endfor %}'
```
Comment (christinaholtNOAA) [inline parm/wflow/verify_det.yaml]:
```suggestion
    METAOB_AVAIL_HRS: '{% for var in verification.VX_FIELD_GROUPS %}{% if var =="SFC" or var =="UPA" %} {{ verification.NDAS_OBS_AVAIL_INTVL_HRS }} {% elif var =="AOD" %}{{ verification.AERONET_OBS_AVAIL_INTVL_HRS }} {% elif var =="PM25" or var =="PM10" %}{{ verification.AIRNOW_OBS_AVAIL_INTVL_HRS }} {% endif %}{% endfor %}'
```

I really don't think these are necessary or have any impact on the outcome. They just add syntax. Maybe I'm wrong?

File: scripts/exregional_run_met_ascii2nc_obs.sh [hunk 10]
```diff
@@ -0,0 +1,376 @@
+#!/usr/bin/env bash
+
+#
```
Comment (christinaholtNOAA) [inline scripts/exregional_run_met_ascii2nc_obs.sh:3]: A doc block here would also be helpful.

File: scripts/exregional_run_met_ascii2nc_obs.sh [hunk 11]
```diff
@@ -0,0 +1,376 @@
...
+#-----------------------------------------------------------------------
+#
+# Export variables needed in the common METplus configuration file (at
+# ${METPLUS_CONF}/common.conf).
+#
+#-----------------------------------------------------------------------
+#
+export METPLUS_CONF
+export LOGDIR
```
Comment (christinaholtNOAA) [inline scripts/exregional_run_met_ascii2nc_obs.sh:211]: Do these have values? Where are those set prior to this point in the script? Why do they need to be exported? What uses them downstream?

File: scripts/exregional_run_met_ascii2nc_obs.sh [hunk 12]
```diff
@@ -0,0 +1,376 @@
...
+#
+# Define variables that appear in the jinja template.
+#
+settings="\
+#
+# MET/METplus information.
+#
+  'metplus_tool_name': '${metplus_tool_name}'
+  'MetplusToolName': '${MetplusToolName}'
+  'METPLUS_TOOL_NAME': '${METPLUS_TOOL_NAME}'
```
Comment (christinaholtNOAA) [inline scripts/exregional_run_met_ascii2nc_obs.sh:272]: Why are all three of these needed? Seems like the same information repeated a lot.

File: ush/config_defaults.yaml [hunk 13]
```diff
@@ -2410,8 +2411,9 @@ verification:
   # -------------------------------
   #
   # METPLUS_VERBOSITY_LEVEL: 
-  # Logging verbosity level used by METplus verification tools.  0 to 5,
-  # with 0 quiet and 5 loudest.
+  # Logging verbosity level used by METplus verification tools.  0 to 9,
+  # with 0 having the fewest log messages and 9 having the most. Levels 5
+  # and above can result in very large log files and slower tool execution..
```
Comment (christinaholtNOAA) [inline ush/config_defaults.yaml]:
```suggestion
  # and above can result in very large log files and slower tool execution.
```

File: ush/generate_FV3LAM_wflow.py [hunk 14]
```diff
@@ -167,392 +168,132 @@ def generate_FV3LAM_wflow(
     #
     # -----------------------------------------------------------------------
     #
-    # From here on out, going back to setting variables for everything
-    # in the flattened expt_config dictionary
-    # TODO: Reference all these variables in their respective
-    # dictionaries, instead.
-    import_vars(dictionary=flatten_dict(expt_config))
-    export_vars(source_dict=flatten_dict(expt_config))
```
Comment (christinaholtNOAA) [inline ush/generate_FV3LAM_wflow.py:175]: YESSSS!

File: ush/generate_FV3LAM_wflow.py [hunk 15]
```diff
@@ -812,6 +559,248 @@ def generate_FV3LAM_wflow(
...
+    Returns:
+        EXPTDIR (str) : The full path of the directory where this experiment has been generated
+    """
+
+    # From here on out, going back to setting variables for everything
+    # in the flattened expt_config dictionary
+    # TODO: Reference all these variables in their respective
+    # dictionaries, instead.
+    import_vars(dictionary=flatten_dict(expt_config))
+    export_vars(source_dict=flatten_dict(expt_config))
```
Comment (christinaholtNOAA) [inline ush/generate_FV3LAM_wflow.py:578]: I made some similar clean up changes in my PR. I find that it's safer to limit the sections that you export here and you can avoid flattening for this section for the most part with:

```
export_vars(source_dict=expt_config["global"])
```

File: ush/machine/derecho.yaml [hunk 16]
```diff
@@ -3,11 +3,13 @@ platform:
...
-  TEST_NDAS_OBS_DIR: /glade/work/epicufsrt/contrib/UFS_SRW_data/develop/obs_data/ndas/proc
-  TEST_NOHRSC_OBS_DIR: /glade/work/epicufsrt/contrib/UFS_SRW_data/develop/obs_data/nohrsc/proc
-  DOMAIN_PREGEN_BASEDIR: /glade/work/epicufsrt/contrib/UFS_SRW_data/develop/FV3LAM_pregen
+  TEST_CCPA_OBS_DIR: '{{ platform.WE2E_TEST_DATA }}/obs_data/ccpa/proc'
+  TEST_MRMS_OBS_DIR: '{{ platform.WE2E_TEST_DATA }}/obs_data/mrms/proc'
+  TEST_NDAS_OBS_DIR: '{{ platform.WE2E_TEST_DATA }}/obs_data/ndas/proc'
+  TEST_NOHRSC_OBS_DIR: '{{ platform.WE2E_TEST_DATA }}/obs_data/nohrsc/proc'
+  TEST_AERONET_OBS_DIR: '{{ platform.WE2E_TEST_DATA }}/obs_data/aeronet'
+  TEST_AIRNOW_OBS_DIR: '{{ platform.WE2E_TEST_DATA }}/obs_data/airnow'
+  DOMAIN_PREGEN_BASEDIR: '{{ platform.WE2E_TEST_DATA }}/FV3LAM_pregen'
```
Comment (christinaholtNOAA) [inline ush/machine/derecho.yaml:12]: Nice.

**Review by christinaholtNOAA — APPROVED** [review]
I've left some change requests for minor changes that should be made and a few others that are optional. A few are questions that could lead to a new comment line. I don't need to review it again.

File: doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst [hunk 17]
```diff
@@ -1854,7 +1866,7 @@ VX Parameters for Observations
       {{- "ccpa.t{valid?fmt=%H}z." ~ obs_avail_intvl_hrs ~ "h.hrap.conus.gb2_a${ACCUM_HH}h.nc" }}
 
    METplus template for the names of the NetCDF files generated by the
-   worfklow verification tasks that call METplus's PcpCombine tool on
+   workflow verification tasks that call METplus's PcpCombine tool on
```
Comment (gsketefian) [inline doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst:1869]: `worfklow` sounds way cooler.

File: parm/wflow/verify_det.yaml [hunk 18]
```diff
@@ -136,49 +136,60 @@ metatask_GridStat_REFC_RETOP_all_mems:
...
               age: 00:00:00:30
             text: !cycstr '{{ workflow.EXPTDIR }}/@Y@m@d@H/post_files_exist_mem#mem#.txt'
+          or:
+            not:
+              taskvalid:
+                attrs:
+                  task: 'run_MET_PcpCombine_fcst_#FIELD_GROUP#_mem#mem#'
+            taskdep:
+              attrs:
+                task: 'run_MET_PcpCombine_fcst_#FIELD_GROUP#_mem#mem#'
```
Comment (gsketefian) [inline parm/wflow/verify_det.yaml:195]: @mkavulich Is this new dependency because one or more of the new obs types (AERONET and AIRNOW) require PcpCombine to be run on the forecast but SFC and UPA do not?

File: ush/setup.py [hunk 19]
```diff
@@ -778,6 +791,23 @@ def _remove_tag(tasks, tag):
...
+        vx_metatasks_all_by_obtype["AIRNOW"] \
+        = ["task_get_obs_airnow",
+           "metatask_ASCII2nc_obs"
+           "metatask_PcpCombine_fcst_PM_all_mems"]
+
+        vx_field_groups_all_by_obtype["AERONET"] = ["AOD"]
+        vx_metatasks_all_by_obtype["AERONET"] = ["task_get_obs_aeronet","metatask_ASCII2nc_obs"]
+
+        vx_field_groups_all_by_obtype["AIRNOW"] = ["PM25","PM10"]
+        vx_metatasks_all_by_obtype["AIRNOW"] = ["task_get_obs_airnow","metatask_ASCII2nc_obs","metatask_PcpCombine_fcst_PM_all_mems"]
```
Comment (gsketefian) [inline ush/setup.py]: @mkavulich Looks like the first two sections are repeated in sections 3 and 4 except with everything on a single line.  I guess remove the first two or last two stanzas/sections.

**Comment by gsketefian** [comment]
@mkavulich I only had a couple of comments.  Looks good.  Approving now.

**Review by gsketefian — APPROVED** [review]

**Comment by gsketefian** [comment]
@mkavulich I haven't gotten a chance to run that test case for checking the timing when pulling one of the new obs types.  I think you said that is not urgent for the code slush, but let me know if you need me to do that.  Thanks.

File: scripts/exregional_run_met_ascii2nc_obs.sh (hunk 12 above)
Comment (mkavulich) [reply scripts/exregional_run_met_ascii2nc_obs.sh:272]: Unfortunately MET and METplus have a mix of capitalization and punctuation conventions for tools at various layers, so we need to maintain separate entries here. There may be more elegant ways to handle this, but this actually prevents the repetition of a lot of logic.

File: doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst (hunk 3 above)
Comment (mkavulich) [reply doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst:636]: "rename" in this case is a noun, so it is a full sentence (just missing a period). With an added period is this wording okay?

File: doc/UsersGuide/Reference/Glossary.rst (hunk 5 above)
Comment (mkavulich) [reply doc/UsersGuide/Reference/Glossary.rst:19]: ReadTheDocs automatically renders text urls as hyperlinks; this is done elsewhere in the Glossary so I assume it's okay.

File: jobs/JREGIONAL_RUN_MET_ASCII2NC_OBS (hunk 7 above)
Comment (mkavulich) [reply jobs/JREGIONAL_RUN_MET_ASCII2NC_OBS:3]: Done, also removed some unnecessary yaml sections.

File: parm/wflow/verify_det.yaml (hunk 8 above)
Comment (mkavulich) [reply parm/wflow/verify_det.yaml:141]: Fixed this one, but the rest are "if/else" statements so I don't think this solution works well

File: scripts/exregional_run_met_ascii2nc_obs.sh (hunk 10 above)
Comment (mkavulich) [reply scripts/exregional_run_met_ascii2nc_obs.sh:3]: Since no other tasks in verification have a doc block here, I'll decline to add if here for now, but something to add for the future.

File: scripts/exregional_run_met_ascii2nc_obs.sh (hunk 11 above)
Comment (mkavulich) [reply scripts/exregional_run_met_ascii2nc_obs.sh:211]: `LOGDIR` is set at the rocoto task level, and `METPLUS_CONF` comes from the config file. These variables are needed because they are referenced in the main METplus `common.conf` file.

**Comment by MichaelLueken** [comment]
The UFS_FIRE WE2E tests successfully passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
UFS_FIRE_multifire_two-way-coupled_20250227081110                  COMPLETE              30.90
UFS_FIRE_one-way-coupled_20250227081112                            COMPLETE              29.16
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE              60.06
```
as well as the AQM WE2E test:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
aqm_grid_AQM_NA13km_suite_GFS_v16_20250227090806                   COMPLETE            3358.64
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            3358.64
```

File: ush/setup.py (hunk 19 above)
Comment (mkavulich) [reply ush/setup.py]: Thanks for catching this, this was just a bad merge resolution. Fixed.

File: parm/wflow/verify_det.yaml (hunk 18 above)
Comment (mkavulich) [reply parm/wflow/verify_det.yaml:195]: This new dependency is needed for PM2.5 coming from the model output; it is split among two different fields, so those must be combined in order to get the correct results from PointStat (see the changes to [PcpCombine.conf](https://github.com/ufs-community/ufs-srweather-app/pull/1174/files#diff-ee331a22c1334355a04e0acf65f14522356435395d2b44efe009989027de8291) and [exregional_run_met_pcpcombine.sh](https://github.com/ufs-community/ufs-srweather-app/pull/1174/files#diff-214ff57ffb0f892cd9b4857bc730e5fa291699aefcb46a0d8e708971e424e9e9))

**Review by mkavulich — COMMENTED** [review]
@christinaholtNOAA I believe I have resolved all your suggestions. Let me know if you have anything else!

**Comment by mkavulich** [comment]
@gsketefian that's correct, if a bug fix is needed for those non-00z ob times then we can apply it to the release branch after the slush. But we should probably get to it in the next week to make sure we have enough time.

**Comment by mkavulich** [comment]
@MichaelLueken I am seeing a failure after my last round of suggested changes; I will let you know when this is ready for testing.

**Comment by mkavulich** [comment]
Okay @MichaelLueken @christinaholtNOAA @gsketefian I have now applied what I think are the final changes, and all verification and fundamental tests are passing on Hera. I think this PR is ready for final tests.

**Comment by MichaelLueken** [comment]
Thanks, @mkavulich!  Launching tests now.

**Comment by MichaelLueken** [comment]
@mkavulich -

The Derecho, Gaea-C5, Hera Intel, and Hercules WE2E coverage tests have successfully passed via Jenkins automated testing.

The Gaea-C6 runner is down, the Hera GNU tests were aborted for running over the eight hour time limit, and the skill-score test failed on Orion.

I'm running the Gaea-C6 tests manually and will kick off the Hera GNU tests once again, but there is an issue that was missed for the skill-score test on Orion:

Please update the `parm/metplus/STATAnalysisConfig_skill_score` parameter file so that the version of MET version used is `12.0.1` rather than `11.1.0`.  The line in question is https://github.com/ufs-community/ufs-srweather-app/blob/33f45876dea0940be5ba964853771faa12212183/parm/metplus/STATAnalysisConfig_skill_score#L151

Once this line is updated, I will also relaunch the Orion coverage tests.

**Comment by mkavulich** [comment]
@MichaelLueken I have made the suggested change.

Which jobs hit the time limit on Hera GNU? If it's verification tests only, we have noticed that newer versions of MET run very slowly with GNU compilers; it may be worth considering swapping out some of the more compute-intensive verification tests to another coverage suite.

**Comment by MichaelLueken** [comment]
@mkavulich -

The only test that runs long on Hera GNU is the `MET_ensemble_verification_only_vx_time_lag` WE2E test.  Currently, there is one task that takes over four hours to complete, but the update to MET and METplus appears to have made the `run_MET_GenEnsProd_vx_SFC` task run even longer, resulting in the task failing and relaunching, hitting the 8 hour walltime allowed to run the Test phase in Jenkins.  It should be fine to move this test to Hera Intel and move one of the Hera Intel verification tests to Hera GNU.

Also, on Gaea-C6, the smoke and dust WE2E, `smoke_dust_grid_RRFS_CONUS_3km_suite_HRRR_gf`, test is seg faulting in the run_fcst task.  I'm attempting to run this test on Hera now to see if the issue is universal across machines or only affecting Gaea-C6.

**Comment by MichaelLueken** [comment]
@mkavulich -

The problem task is `run_MET_GenEnsProd_vx_UPA`, not `run_MET_GenEnsProd_vx_SFC` (though `run_MET_GenEnsProd_vx_SFC` does run for close to three hours itself).

**Comment by mkavulich** [comment]
That makes sense. GenEnsProd is one of the most compute-intensive MET utilities, and UPA has the most data. I suspect moving that test (and any other ensemble vx tests) out of the GNU coverage suite will solve the issue.

**Comment by MichaelLueken** [comment]
I agree, if you move the `MET_ensemble_verification_only_vx_time_lag` WE2E test out of the [coverage.hera.gnu.com](https://github.com/ufs-community/ufs-srweather-app/blob/develop/tests/WE2E/machine_suites/coverage.hera.gnu.com) suite, then the Hera GNU tests will pass without issue.

Unfortunately, the seg faulting of the `smoke_dust_grid_RRFS_CONUS_3km_suite_HRRR_gf` WE2E test is also happening on Hera as well.  It is happening at the same point:
```
 in fv3cap init, time wrtcrt/regrdst   9.02738700807095
 in fv3 cap init, output_startfh=  0.0000000E+00  iau_offset=           0
 output_fh=  9.9999998E-03   1.000000       2.000000       3.000000
   4.000000       5.000000       6.000000     lflname_fulltime= F
 fcst_advertise, cpl_grid_id=           1
 fcst_realize, cpl_grid_id=           1
  aft fcst run output time=          36 FBcount=           8 na=           1
[h3c11:3253333:1:3253429] Caught signal 11 (Segmentation fault: Sent by the kernel at address (nil))
```
for both Gaea-C6 and Hera.  Can you think of any of your changes that could potentially be adversely affecting the smoke and dust capability in the weather model?

**Comment by mkavulich** [comment]
@MichaelLueken can you point me to the failing test run directory on Hera? And if possible, a successful test from some other PR?

**Comment by MichaelLueken** [comment]
@mkavulich -

The failed test from your PR on Hera is available - /scratch1/NCEPDEV/stmp2/Michael.Lueken/ufs-srweather-app/expt_dirs/smoke_dust_grid_RRFS_CONUS_3km_suite_HRRR_gf

Since the tests for PRs are only run on Gaea-C6, I'll kick off a test using the current develop on Hera and provide you the path once it has started.

**Comment by MichaelLueken** [comment]
@mkavulich -

The current HEAD of develop has made it past the part that seg faults on Hera without issue - /scratch1/NCEPDEV/stmp2/Michael.Lueken/expt_dirs/smoke_dust_grid_RRFS_CONUS_3km_suite_HRRR_gf

**Comment by mkavulich** [comment]
@MichaelLueken I think I have fixed the issue; when I merged in the latest develop I missed a line that did not update LEVP correctly in `external_ic_nml`. If you re-generate the experiment (shouldn't need a re-build) with the change I just pushed I think it should succeed.

Side note, but this is a great example of a problem that would have been caught by the type of component-level tests I proposed to @benkozi that he documented in [this discussion](https://github.com/ufs-community/ufs-srweather-app/discussions/1216), and wouldn't have wasted so much time and resources having to re-run full tests and manually check them. Seeing that the namelists didn't match would have let me know ahead of time that there was a problem.

**Comment by MichaelLueken** [comment]
@mkavulich -

I've updated my clone of your branch and relaunched the `smoke_dust_grid_RRFS_CONUS_3km_suite_HRRR_gf` WE2E test.  I'll let you know if the seg faults continue, otherwise, I should be able to post the successful log for Gaea-C6.

With respect to the Hera GNU `MET_ensemble_verification_only_vx_time_lag` test, either moving it to Hera Intel or increasing the walltime for the `run_MET_GenEnsProd_vx_UPA` to 04:30:00 should allow this test to pass.  The rest of the WE2E tests successfully pass on Hera GNU:
```
log.run_WE2E_tests:root             INFO     Experiment MET_verification_only_vx_20250228144938 is COMPLETE
log.run_WE2E_tests:root             INFO     Experiment vx-det_multicyc_last-obs-00z_ncep-hrrr_20250228144954 is COMPLETE
log.run_WE2E_tests:root             INFO     Experiment get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2019061200_20250228144932 is COMPLETE
log.run_WE2E_tests:root             INFO     Experiment vx-det_long-fcst_winter-wx_SRW-staged_20250228144947 is COMPLETE
log.run_WE2E_tests:root             INFO     Experiment get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS_20250228144932 is COMPLETE
log.run_WE2E_tests:root             INFO     Experiment grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20250228144935 is COMPLETE
log.run_WE2E_tests:root             INFO     Experiment vx-det_long-fcst_custom-vx-config_aiml-panguweather_20250228144944 is COMPLETE
log.run_WE2E_tests:root             INFO     Experiment vx-det_long-fcst_custom-vx-config_aiml-fourcastnet_20250228144943 is COMPLETE
log.run_WE2E_tests:root             INFO     Experiment vx-det_long-fcst_custom-vx-config_gfs_20250228144946 is COMPLETE
log.run_WE2E_tests:root             INFO     Experiment vx-det_multicyc_fcst-overlap_ncep-hrrr_20250228144953 is COMPLETE
log.run_WE2E_tests:root             INFO     Experiment grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta_20250228144934 is COMPLETE
log.run_WE2E_tests:root             INFO     Experiment custom_ESGgrid_Central_Asia_3km_20250228144929 is COMPLETE
log.run_WE2E_tests:root             INFO     Experiment grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_20250228144933 is COMPLETE
log.run_WE2E_tests:root             INFO     Experiment long_fcst_20250228144937 is COMPLETE
log.run_WE2E_tests:root             INFO     Experiment 2019_halloween_storm_20250228144941 is COMPLETE
log.run_WE2E_tests:root             INFO     Experiment 2020_jan_cold_blast_20250228144942 is COMPLETE
```

**Comment by MichaelLueken** [comment]
@mkavulich -

I'm testing again on Hera, but the Gaea-C6 `smoke_dust_grid_RRFS_CONUS_3km_suite_HRRR_gf` test failed again with a seg fault after updating `ush/generate_FV3LAM_wflow.py`.  Looking in `input.nml`, I see:

```
&external_ic_nml
    checker_tr = .false.
    filtered_terrain = .true.
    gfs_dwinds = .true.
    levp = 65
    nt_checker = 0
/
```

while the value of `levp` should be `66` for the smoke and dust test.  I'll keep you addressed of what i discover while testing on Hera.

**Comment by mkavulich** [comment]
@MichaelLueken I think I have spotted the problem: I pushed another change that should hopefully fix it. It was another merge-related problem related to vertical levels (this time the `npz` setting); both seemed to come from resolving conflicts with my initial UFS_FIRE PR. I reviewed the rest of the changes and I *think* there should no longer be any bad merge resolution items.

Strangely, I wasn't able to reproduce this problem by modifying tests like `grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR` to have an inconsistent number of vertical levels. So apparently this segfault condition is specific to smoke/dust or some other condition, even though the incorrect vertical levels might be used "successfully" in other cases. Because of this I'm not 100% sure that this latest change fixes the problem, but I am hopeful.

**Comment by MichaelLueken** [comment]
The automated tests have successfully passed on Orion following your update to the skill-score parm file:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
2020_CAD_20250228135149                                            COMPLETE              88.20
custom_ESGgrid_SF_1p1km_20250228135151                             COMPLETE             583.84
deactivate_tasks_20250228135153                                    COMPLETE               1.90
get_from_AWS_ics_GEFS_lbcs_GEFS_fmt_grib2_2022040400_ensemble_2me  COMPLETE            2096.73
grid_CONUS_3km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta_  COMPLETE             731.33
grid_RRFS_AK_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot_20250  COMPLETE             203.44
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_RRFS_v1beta_202502281  COMPLETE              29.30
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_20250228135  COMPLETE            1027.29
grid_RRFS_CONUScompact_25km_ics_RRFS_lbcs_RRFS_suite_RRFS_v1beta_  COMPLETE              25.68
grid_RRFS_CONUScompact_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_  COMPLETE              85.62
grid_RRFS_CONUScompact_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_2  COMPLETE             800.28
grid_SUBCONUS_Ind_3km_ics_FV3GFS_lbcs_FV3GFS_suite_WoFS_v0_202502  COMPLETE              59.11
MET_verification_smoke_only_vx_20250228135213                      COMPLETE               1.02
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            5733.74
```

**Comment by MichaelLueken** [comment]
@mkavulich -

I'm in the process of opening a PR into your `feature/add_smoke_vx` branch that will finish the necessary modifications to get this PR merged.  It will:
1. Move the `MET_ensemble_verification_only_vx_time_lag` WE2E test out of the Hera GNU suite and into the Hera Intel suite.  Since this WE2E test needs to be run on all platforms as part of the comprehensive test suite, I have increased the walltime for the run_MET_GenEnsProd_vx_UPA task so that it will run on GNU-built executables.
2. Point to `https://metplus.readthedocs.io/projects/met/en/latest/Users_Guide/reformat_point.html#ascii2nc-tool` rather than `https://met.readthedocs.io/projects/met/en/latest/Users_Guide/reformat_point.html#ascii2nc-tool`, as the met URL is no longer available and causes the documentation to fail.
3. Add back the `levp` update in `ush/generate_FV3LAM_wflow.py`.  This needs to be in the workflow generation, otherwise `levp` will default to `65`, rather than the expected `66` for smoke and dust.

**Comment by MichaelLueken** [comment]
@mkavulich -

PR [#3](https://github.com/mkavulich/ufs-srweather-app/pull/3) has been opened in your fork to merge the final changes into your `feature/add_smoke_vx` branch so that this PR can get merged.  The Gaea-C6 WE2E tests are now passing successfully with these changes:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
community_20250303105852                                           COMPLETE              22.77
custom_ESGgrid_NewZealand_3km_20250303105853                       COMPLETE              77.21
grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              36.65
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RAP_20250303105  COMPLETE              39.55
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_2025030310  COMPLETE              38.87
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson  COMPLETE             415.82
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2025030  COMPLETE              32.96
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_20  COMPLETE             429.50
grid_SUBCONUS_Ind_3km_ics_RAP_lbcs_RAP_suite_RRFS_v1beta_plot_202  COMPLETE              11.06
smoke_dust_grid_RRFS_CONUS_3km_suite_HRRR_gf_20250303105857        COMPLETE            1216.59
2020_CAPE_20250303105858                                           COMPLETE              41.68
2020_easter_storm_20250303105859                                   COMPLETE              42.48
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            2405.14
```
So, I can move forward with merging this PR once PR 3 has been merged into the `feature/add_smoke_vx` branch.  Thanks!

**Comment by MichaelLueken** [comment]
Thanks for merging my PR, @mkavulich!

I was able to verify that both `"npz": LEVP - 1,` and `settings["external_ic_nml"] = {"levp": LEVP}` are in the `ush/generate_FV3LAM_wflow.py` script in your `feature/add_smoke_vx` branch.

I will now move forward with merging this PR now.
