### PR TITLE
[develop] MET_verification: use modules met, metplus 

### LINKED ISSUE #863: Verification tests `MET_verification_only_vx`, `MET_ensemble_verification_only_vx`, and `MET_ensemble_verification_only_vx_time_lag` fail on most platforms despite data being staged
## Expected behavior
Tests `MET_verification_only_vx`, `MET_ensemble_verification_only_vx`, and `MET_ensemble_verification_only_vx_time_lag` should succeed on platforms where data has been staged.

## Current behavior
Currently these tasks only succeed on Hera. On other platforms, the experiments fail in the "`check_post_output*`" task(s). These platforms need to have the variable  `TEST_VX_FCST_INPUT_BASEDIR` set to point to the staged data

## Machines affected
All except Hera

## Steps To Reproduce
Attempt to run one of the above-mentioned tests on any platform except Hera

## Detailed Description of Fix (optional)
Set `TEST_VX_FCST_INPUT_BASEDIR` appropriately on all platforms

### PR DESCRIPTION
**Pull request by natalie-perlin**
## DESCRIPTION OF CHANGES: 

- Use modules met and metplus installed in a software stack for MET verification tasks. Do not use explicitly set paths in machine files or config.yaml files. Use env. variables METPLUS_PATH, MET_INSTALL_DIR from the modulefiles. Retire MET_BIN_EXEC variables, use standard "bin". Modules met/10.1.2 and metplus/4.1.3 are used. Newer versions, met/11.0.2 and metplus/5.0.2 require additional code changes.

- Updated Orion stack location due to a mandatory transition to a new role account and space, under /work/noaa/epic/role-epic/. New stack is under /work/noaa/epic/role-epic/contrib/orion/hpc-stack/intel-2022.1.2/ . SRW fundamental tests have been run successfully with the updates stack, as well as GSI regression tests and UFS-WM regression tests. PR-1846 to the weather model repo has been submitted: https://github.com/ufs-community/ufs-weather-model/pull/1846 .
Miniconda3 with all the environments has been installed in a new Orion location, under **/work/noaa/epic/role-epic/contrib/orion/miniconda3/** and updated in modulefiles. 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## TESTS CONDUCTED: 

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [ ] cheyenne.intel
- [x] cheyenne.gnu (partially)
- [ ] gaea.intel
- [x] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## DEPENDENCIES:

The  current PR resolves the issue https://github.com/ufs-community/ufs-srweather-app/issues/863 .

## DOCUMENTATION:

Preliminary changes to documentation in files:
./docs/UsersGuide/source/ConfigWorkflow.rst
./docs/UsersGuide/source/RunSRW.rst
./docs/UsersGuide/source/VXCases.rst
## CHECKLIST

- [x] My code follows the style guidelines in the Contributor's Guide
- [x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [ ] bug
- [x] enhancement
- [x] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [x] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ x] Needs Orion test 
- [ ] help wanted

### CODE REVIEW

**Comment by gsketefian** [comment]
@natalie-perlin Thanks for switching MET/METplus to the official software stacks.  Couple of questions:
1) Have the 4 verification tests (in `tests/WE2E/test_configs/verification`) passed with the slightly newer versions you're using in this PR?
2) Does the software stack on Hera have the METplus 5.0 coordinated release installed ([this one](https://dtcenter.org/community-code/metplus/coordinated-metplus-version-5-0))?  That includes MET 11.0.2 and METplus 5.0.2.  Just curious since there are certain features we (the DTC) would like to implement that are only available in newer versions.

Thanks.

**Comment by MichaelLueken** [comment]
@natalie-perlin Since this PR will correct the the failure of the grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16 fundamental WE2E test on Cheyenne GNU, I will go ahead and close PR #820 at this time.

**Comment by natalie-perlin** [comment]
@gsketefian - 
1. Is shortcut to run all the `verification` tests, or they need to be added to a list in a specific file, such as my_tests.txt and run these specific tests? I.e., something like 
`./run_WE2E_tests.py -t verification -m cheyenne -a ...`

2. I could definitely test and install the new MET and METplus packages with the current stacks, and test it with the existing data. Could there be some kind of a request to update these packages using "GitHub issues", or "Gihub discussions"?

**Comment by gsketefian** [comment]
> @gsketefian -
> 
> 1. Is shortcut to run all the `verification` tests, or they need to be added to a list in a specific file, such as my_tests.txt and run these specific tests? I.e., something like
>    `./run_WE2E_tests.py -t verification -m cheyenne -a ...`
> 2. I could definitely test and install the new MET and METplus packages with the current stacks, and test it with the existing data. Could there be some kind of a request to update these packages using "GitHub issues", or "Gihub discussions"?

@natalie-perlin:
1. There isn't a shortcut, I just call the `run_WE2E_tests.py` script with a `my_tests.txt` that contains the 5 vx tests (I said 4 before, but now there are actually 5):
```
MET_ensemble_verification
MET_ensemble_verification_only_vx
MET_ensemble_verification_only_vx_time_lag
MET_verification
MET_verification_only_vx
```
2. Let me create an issue in GitHub for upgrading the MET/METplus packages and see if the vx team at DTC are all ok with it.  If so, it would be great if you can test with the new versions.  It's not urgent, so it doesn't have to be part of this PR.

Thanks!

**Comment by gsketefian** [comment]
@natalie-perlin I created an issue regarding a MET/METplus upgrade at #834.  Feel free to comment there.

File: scripts/exregional_run_met_pcpcombine.sh [hunk 1]
```diff
@@ -246,7 +246,6 @@ fi
 #
 export MET_INSTALL_DIR
```
Comment (gsketefian) [inline scripts/exregional_run_met_pcpcombine.sh]: @natalie-perlin Should `MET_INSTALL_DIR` and `METPLUS_PATH` also be removed from this and the other `exregional_...` scripts since they're being removed from `config_defaults.yaml`?

**Comment by gsketefian** [comment]
@natalie-perlin Just getting back to this to see if the 5 vx tests run with this PR.  Thanks.

File: scripts/exregional_run_met_pcpcombine.sh (hunk 1 above)
Comment (natalie-perlin) [reply scripts/exregional_run_met_pcpcombine.sh]: Yes, they would be removed, and instead replaced by loading met and metplus modules.

**Comment by natalie-perlin** [comment]
@gsketefian - 
 I ran the tests on Gaea with  met/11.0.2 and metplus/5.0.2, one of the fundamental suite tests grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16 that has many verification tasks. Here is the status from rocoto (showing the last relevant tasks):
 
```
 202105121200       run_MET_Pb2nc_obs                   206556492           SUCCEEDED                   0         1         181.0
202105121200    run_MET_PcpCombine_obs_APCP01h                   206556498           SUCCEEDED                   0         1         154.0
202105121200    run_MET_PcpCombine_obs_APCP03h                   206556500           SUCCEEDED                   0         1         152.0
202105121200    run_MET_PcpCombine_obs_APCP06h                   206556502           SUCCEEDED                   0         1         151.0
202105121200    check_post_output_mem001                   206556718           SUCCEEDED                   0         1         163.0
202105121200    check_post_output_mem002                   206556720           SUCCEEDED                   0         1         162.0
202105121200    run_MET_PcpCombine_fcst_APCP01h_mem001                   206556724           SUCCEEDED                   0         1          63.0
202105121200    run_MET_PcpCombine_fcst_APCP01h_mem002                   206556726           SUCCEEDED                   0         1         156.0
202105121200    run_MET_PcpCombine_fcst_APCP03h_mem001                   206556728           SUCCEEDED                   0         1          58.0
202105121200    run_MET_PcpCombine_fcst_APCP03h_mem002                   206556730           SUCCEEDED                   0         1          59.0
202105121200    run_MET_PcpCombine_fcst_APCP06h_mem001                   206556732           SUCCEEDED                   0         1          58.0
202105121200    run_MET_PcpCombine_fcst_APCP06h_mem002                   206556734           SUCCEEDED                   0         1         153.0
202105121200    run_MET_GridStat_vx_APCP01h_mem001                   206556756           SUCCEEDED                   0         1          63.0
202105121200    run_MET_GridStat_vx_APCP01h_mem002                   206556758           SUCCEEDED                   0         1          63.0
202105121200    run_MET_GridStat_vx_APCP03h_mem001                   206556760           SUCCEEDED                   0         1          44.0
202105121200    run_MET_GridStat_vx_APCP03h_mem002                   206556762           SUCCEEDED                   0         1          43.0
202105121200    run_MET_GridStat_vx_APCP06h_mem001                   206556764           SUCCEEDED                   0         1          41.0
202105121200    run_MET_GridStat_vx_APCP06h_mem002                   206556766           SUCCEEDED                   0         1         129.0
202105121200    run_MET_GridStat_vx_REFC_mem001                   206556736           SUCCEEDED                   0         1         262.0
202105121200    run_MET_GridStat_vx_RETOP_mem001                   206556738           SUCCEEDED                   0         1         168.0
202105121200    run_MET_GridStat_vx_REFC_mem002                   206556740           SUCCEEDED                   0         1         161.0
202105121200    run_MET_GridStat_vx_RETOP_mem002                   206556742           SUCCEEDED                   0         1         167.0
202105121200    run_MET_PointStat_vx_SFC_mem001                   206556744           SUCCEEDED                   0         1          84.0
202105121200    run_MET_PointStat_vx_UPA_mem001                   206556746           SUCCEEDED                   0         1         154.0
202105121200    run_MET_PointStat_vx_SFC_mem002                   206556748           SUCCEEDED                   0         1          84.0
202105121200    run_MET_PointStat_vx_UPA_mem002                   206556750           SUCCEEDED                   0         1          70.0
202105121200    run_MET_GenEnsProd_vx_APCP01h                   206556768           SUCCEEDED                   0         1         155.0
202105121200    run_MET_EnsembleStat_vx_APCP01h                   206556827                DEAD                   1         2         143.0
202105121200    run_MET_GenEnsProd_vx_APCP03h                   206556770           SUCCEEDED                   0         1          41.0
202105121200    run_MET_EnsembleStat_vx_APCP03h                   206556829                DEAD                   1         2         130.0
202105121200    run_MET_GenEnsProd_vx_APCP06h                   206556772           SUCCEEDED                   0         1          39.0
202105121200    run_MET_EnsembleStat_vx_APCP06h                   206556831                DEAD                   1         2          47.0
202105121200    run_MET_GenEnsProd_vx_REFC                   206556774           SUCCEEDED                   0         1         169.0
202105121200    run_MET_EnsembleStat_vx_REFC                   206556833                DEAD                   1         2          72.0
202105121200    run_MET_GenEnsProd_vx_RETOP                   206556776           SUCCEEDED                   0         1         170.0
202105121200    run_MET_EnsembleStat_vx_RETOP                   206556835                DEAD                   1         2          70.0
202105121200    run_MET_GenEnsProd_vx_SFC                   206556778           SUCCEEDED                   0         1         175.0
202105121200    run_MET_EnsembleStat_vx_SFC                   206556837                DEAD                   1         2          52.0
202105121200    run_MET_GenEnsProd_vx_UPA                   206556780           SUCCEEDED                   0         1         145.0
202105121200    run_MET_EnsembleStat_vx_UPA                   206556839                DEAD                   1         2          46.0
202105121200    run_MET_GridStat_vx_ensmean_APCP01h                   206556800           SUCCEEDED                   0         1         151.0
202105121200    run_MET_GridStat_vx_ensmean_APCP03h                   206556802           SUCCEEDED                   0         1         132.0
202105121200    run_MET_GridStat_vx_ensmean_APCP06h                   206556804           SUCCEEDED                   0         1         129.0
202105121200    run_MET_GridStat_vx_ensprob_APCP01h                   206556806           SUCCEEDED                   0         1          60.0
202105121200    run_MET_GridStat_vx_ensprob_APCP03h                   206556808           SUCCEEDED                   0         1          38.0
202105121200    run_MET_GridStat_vx_ensprob_APCP06h                   206556810           SUCCEEDED                   0         1         131.0
202105121200    run_MET_GridStat_vx_ensprob_REFC                   206556812           SUCCEEDED                   0         1         553.0
202105121200    run_MET_GridStat_vx_ensprob_RETOP                   206556814           SUCCEEDED                   0         1         615.0
202105121200    run_MET_PointStat_vx_ensmean_SFC                   206556816           SUCCEEDED                   0         1          64.0
202105121200    run_MET_PointStat_vx_ensmean_UPA                   206556818           SUCCEEDED                   0         1         137.0
202105121200    run_MET_PointStat_vx_ensprob_SFC                   206556820           SUCCEEDED                   0         1         185.0
202105121200    run_MET_PointStat_vx_ensprob_UPA                   206556822           SUCCEEDED                   0         1         142.0
```

So all the *ens* have failed.  Is there anything missing that needs to be set up  for these tasks?
Log files could ve found in `/lustre/f2/dev/role.epic/sandbox/SRW/expt_dirs/grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16/log`.
An example of the error message in `run_MET_EnsembleStat_vx_APCP01h_2021051212.log`:
```
...
Running METplus 5.0.2
Starting METplus v5.0.2
FATAL ERROR: 
ERROR:
  From script:  "exregional_run_met_genensprod_or_ensemblestat.sh"
  Full path to script:  "/lustre/f2/dev/wpo/role.epic/sandbox/SRW/srw-dev-upd/scripts/exregional_run_met_genensprod_or_ensemblestat.sh"
  
Call to METplus failed with return code: 1
METplus configuration file used is:
  metplus_config_fp = "/lustre/f2/dev/wpo/role.epic/sandbox/SRW/expt_dirs/grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16/2021051212/metprd/EnsembleStat/EnsembleStat_APCP01h.conf"
Exiting with nonzero status.
FATAL ERROR: 
ERROR:
  From script:  "JREGIONAL_RUN_MET_GENENSPROD_OR_ENSEMBLESTAT"
  Full path to script:  "/lustre/f2/dev/wpo/role.epic/sandbox/SRW/srw-dev-upd/jobs/JREGIONAL_RUN_MET_GENENSPROD_OR_ENSEMBLESTAT"
Call to ex-script corresponding to J-job "JREGIONAL_RUN_MET_GENENSPROD_OR_ENSEMBLESTAT" failed.
Exiting with nonzero status.

```

Any suggestions on how to approach this issue?

**Comment by natalie-perlin** [comment]
@gsketefian @MichaelLueken -

I've tested a current develop branch for Met and Metplus tests, on Hera intel compiler. The _develop_ branch test fails to generate a "MET_ensemble_verification_only_vx_time_lag" experiment:

```
workflow_tools) [Natalie.Perlin@Hera:/scratch1/NCEPDEV/stmp2/Natalie.Perlin/SRW/srw-dev/tests/WE2E]$ ./run_WE2E_tests.py -t="MET_ensemble_verification_only_vx_time_lag" -m=hera -a=epic --use_cron_to_relaunch --cron_relaunch_intvl_mnts=1 
Checking that all tests are valid
Will run 1 tests:
/scratch1/NCEPDEV/stmp2/Natalie.Perlin/SRW/srw-dev/tests/WE2E/test_configs/verification/config.MET_ensemble_verification_only_vx_time_lag.yaml
Calling workflow generation function for test MET_ensemble_verification_only_vx_time_lag


  ========================================================================
  Starting experiment generation...
  ========================================================================

  ========================================================================
  Starting function setup() in "setup.py"...
  ========================================================================
Found and allowing key task_get_obs_ccpa
Found and allowing key task_get_obs_mrms
Found and allowing key task_get_obs_ndas

*********************************************************************
FATAL ERROR:
Experiment generation failed. See the error message(s) printed below.
For more detailed information, check the log file from the workflow
generation script: log.run_WE2E_tests
*********************************************************************

Traceback (most recent call last):
  File "/scratch1/NCEPDEV/stmp2/Natalie.Perlin/SRW/srw-dev/tests/WE2E/./run_WE2E_tests.py", line 510, in <module>
    run_we2e_tests(homedir,args)
  File "/scratch1/NCEPDEV/stmp2/Natalie.Perlin/SRW/srw-dev/tests/WE2E/./run_WE2E_tests.py", line 207, in run_we2e_tests
    expt_dir = generate_FV3LAM_wflow(ushdir,logfile=f"{ushdir}/log.generate_FV3LAM_wflow",
  File "/scratch1/NCEPDEV/stmp2/Natalie.Perlin/SRW/srw-dev/tests/WE2E/../../ush/generate_FV3LAM_wflow.py", line 71, in generate_FV3LAM_wflow
    expt_config = setup(ushdir,debug=debug)
  File "/scratch1/NCEPDEV/stmp2/Natalie.Perlin/SRW/srw-dev/tests/WE2E/../../ush/setup.py", line 379, in setup
    expt_config = load_config_for_setup(USHdir, default_config_fp, user_config_fp)
  File "/scratch1/NCEPDEV/stmp2/Natalie.Perlin/SRW/srw-dev/tests/WE2E/../../ush/setup.py", line 105, in load_config_for_setup
    raise Exception(errmsg)
Exception: Invalid key(s) specified in /scratch1/NCEPDEV/stmp2/Natalie.Perlin/SRW/srw-dev/ush/config.yaml:
NET = RRFSE_CONUS

Check /scratch1/NCEPDEV/stmp2/Natalie.Perlin/SRW/srw-dev/ush/config_defaults.yaml for allowed user-specified variables
```

Checking ./ush/config_defaults.yaml  doesn't really give an idea about expected values for NET, but I could only guess this might be a typo, and it needs to be something like NET = RRFSE_CONUS in ./ush/config.yaml. The config.yaml is test-specific,  where the config.yaml file for this test MET_ensemble_verification_only_vx_time_lag is located?..

**Comment by MichaelLueken** [comment]
@natalie-perlin The `MET_ensemble_verification_only_vx_time_lag` configuration file can be found:

`tests/WE2E/test_configs/verification/config.MET_ensemble_verification_only_vx_time_lag.yaml`

To fix the issue you are encountering, replace:

`NET: 'RRFSE_CONUS'`

with

`NET_default: 'RRFSE_CONUS'`

**Comment by natalie-perlin** [comment]
@MichaelLueken - thank you, that's indeed a fix.

@gsketefian - FYI
Tests for Hera:

1) Met/10.1.2 and metplus/4.1.3 modules , in 
/scratch1/NCEPDEV/stmp2/Natalie.Perlin/SRW/expt_dirs/met_old_mod
All met_verification tests except for the one with time-lag pass. All fundamental tests pass.

2) Met/11.0.2 and metplus/5.0.2 - Experiments MET_verification and MET_verification_only_vx all pass; 
some of the tasks for met ensemble verification fail. 
/scratch1/NCEPDEV/stmp2/Natalie.Perlin/SRW/expt_dirs/met_new_mod

I'm investigating reasons for failure with newer module versions.

**Comment by natalie-perlin** [comment]
In testing on `Orion` and `Jet `with the modules:
 The experiments `MET_verification` and `MET_verification_only_vx` that passed OK on Hera, have the following tasks failed: check_post_output_mem000 
 
Checking the reason for failure.

**Comment by natalie-perlin** [comment]
@gsketefian @MichaelLueken - 
After verifying installations of newer modules or met/11.0.2 and metplus/5.0.2, confirming that they do not work in the same way as previous versions met/10.1.2 and metplus/4.1.3.

Errors in the log files indicate the changes that are needed for newer version of metplus:
```
...
07/14 16:18:22.855Z metplus INFO: Config Input: /scratch1/NCEPDEV/stmp2/Natalie.Perlin/SRW/expt_dirs/met_new_mod/MET_ensemble_verification_only_vx/2019061500/metprd/EnsembleStat/EnsembleStat_APCP01h.conf
07/14 16:18:22.855Z metplus (config_validate.py:106) ERROR: DEPRECATED CONFIG ITEMS WERE FOUND. PLEASE FOLLOW THE INSTRUCTIONS TO UPDATE THE CONFIG FILES
07/14 16:18:22.855Z metplus (config_validate.py:109) ERROR: EnsembleStat functionality has been moved to GenEnsProd. The required changes to the config files depend on the type of evaluation that is being performed. Please navigate to the upgrade instructions: https://metplus.readthedocs.io/en/develop/Users_Guide/release-notes.html#metplus-wrappers-upgrade-instructions
07/14 16:18:22.855Z metplus (config_validate.py:109) ERROR: ENSEMBLE_STAT_ENSEMBLE_FLAG_LATLON should be removed
07/14 16:18:22.855Z metplus (config_validate.py:109) ERROR: ENSEMBLE_STAT_ENSEMBLE_FLAG_MEAN should be removed
07/14 16:18:22.855Z metplus (config_validate.py:109) ERROR: ENSEMBLE_STAT_ENSEMBLE_FLAG_STDEV should be removed
07/14 16:18:22.855Z metplus (config_validate.py:109) ERROR: ENSEMBLE_STAT_ENSEMBLE_FLAG_MINUS should be removed
07/14 16:18:22.855Z metplus (config_validate.py:109) ERROR: ENSEMBLE_STAT_ENSEMBLE_FLAG_PLUS should be removed
07/14 16:18:22.855Z metplus (config_validate.py:109) ERROR: ENSEMBLE_STAT_ENSEMBLE_FLAG_MIN should be removed
07/14 16:18:22.855Z metplus (config_validate.py:109) ERROR: ENSEMBLE_STAT_ENSEMBLE_FLAG_MAX should be removed
07/14 16:18:22.855Z metplus (config_validate.py:109) ERROR: ENSEMBLE_STAT_ENSEMBLE_FLAG_RANGE should be removed
07/14 16:18:22.855Z metplus (config_validate.py:109) ERROR: ENSEMBLE_STAT_ENSEMBLE_FLAG_VLD_COUNT should be removed
07/14 16:18:22.855Z metplus (config_validate.py:109) ERROR: ENSEMBLE_STAT_ENSEMBLE_FLAG_FREQUENCY should be removed
07/14 16:18:22.856Z metplus (config_validate.py:109) ERROR: ENSEMBLE_STAT_ENSEMBLE_FLAG_NEP should be removed
07/14 16:18:22.856Z metplus (config_validate.py:109) ERROR: ENSEMBLE_STAT_ENSEMBLE_FLAG_NMEP should be removed
07/14 16:18:22.856Z metplus (config_validate.py:109) ERROR: Please navigate to the upgrade instructions: https://metplus.readthedocs.io/en/develop/Users_Guide/release-notes.html#metplus-wrappers-upgrade-instructions
07/14 16:18:22.857Z metplus (run_util.py:56) ERROR: Correct configuration variables and rerun. Exiting.
07/14 16:18:22.857Z metplus INFO: Check the log file for more information: /scratch1/NCEPDEV/stmp2/Natalie.Perlin/SRW/expt_dirs/met_new_mod/MET_ensemble_verification_only_vx/log/metplus.log.EnsembleStat_APCP01h
Running METplus 5.0.2
Starting METplus v5.0.2
FATAL ERROR:
...
```
It turns out that variable names have changed in version starting 5.0.0, and thus the tests need to be adapted to new var. names:
[ changes for metplus ](https://metplus.readthedocs.io/en/develop/Users_Guide/release-notes.html#metplus-wrappers-upgrade-instructions)

**Comment by natalie-perlin** [comment]
@gsketefian @MichaelLueken - 
should I go ahead and change the variables in Met verif. tests as suggested for versions >=5.0.0? 
Other option could be doing it in two steps: 
1) Use a current PR to switch  using met/10.1.2 and metplus/4.1.3 modules; 
2) move higher versions of met/11.0.2 and metplus/5.0.2

**Comment by gsketefian** [comment]
@natalie-perlin Thanks for testing with the newer versions.  I say let's be conservative and not change versions quite yet (but still switch to using modules).  It would be best if the vx team at the DTC first took a look at the changes required to upgrade to the newer version of METplus to make sure vx results don't change.  I'll put it down as a to-do for one of our projects.  

Once my bugfix PR #868 is merged (and you merge it into your branch), the WE2E test `MET_ensemble_verification_only_vx_time_lag` should pass.  (That PR includes @MichaelLueken 's suggested fix above plus a couple of other fixes.).  I'll keep an eye out and give an approve once that's done.

**Comment by natalie-perlin** [comment]
@gsketefian - thank you for the confirmation!. I'll keep the older versions and proceed with met/10.1.2 and metplus/4.1.3 to finalize tests for this PR :)

**Comment by natalie-perlin** [comment]
After the updates to configuration and modulefiles, all the met verification tests pass on Hera, Orion, and Jet. 
On Orion, a new role-account space has been used for the hpc-stack and miniconda3 + environments (updated the PR description)

File: scripts/exregional_run_met_pcpcombine.sh (hunk 1 above)
Comment (gsketefian) [reply scripts/exregional_run_met_pcpcombine.sh]: @natalie-perlin Could you remove `MET_INSTALL_DIR` and `METPLUS_PATH` from this and the other `exregional_...` scripts?  Thanks.

Comment (natalie-perlin) [reply scripts/exregional_run_met_pcpcombine.sh]: @gsketefian - done. 
Updated the exregional_run_met* files and removed  `MET_INSTALL_DIR` and `METPLUS_PATH` variables that are defined in modulefiles. All the met verification tests ran successfully on Jet after these updates:
```
All 5 experiments finished
Calculating core-hour usage and printing final summary
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
MET_verification                                                   COMPLETE              10.06
MET_verification_only_vx                                           COMPLETE               0.21
MET_ensemble_verification                                          COMPLETE              19.71
MET_ensemble_verification_only_vx                                  COMPLETE               1.23
MET_ensemble_verification_only_vx_time_lag                         COMPLETE               4.91
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE              36.12

Detailed summary written to /mnt/lfs4/HFIP/hfv3gfs/Natalie.Perlin/SRW/expt_dirs/WE2E_summary_20230802150411.txt


```

Comment (gsketefian) [reply scripts/exregional_run_met_pcpcombine.sh]: @natalie-perlin Great, thanks!  Approving now.

**Review by gsketefian — APPROVED** [review]

File: docs/UsersGuide/source/RunSRW.rst [hunk 2]
```diff
@@ -682,16 +675,9 @@ Users who want to use the METplus verification suite to evaluate their forecasts
...
-To use METplus verification, the path to the MET and METplus directories must be added to ``config.yaml``:
-
-.. code-block:: console
-
-   platform:
-      METPLUS_PATH: </path/to/METplus/METplus-4.1.0>
-      MET_INSTALL_DIR: </path/to/met/10.1.0>
-
-To turn on verification tasks in the workflow, include the ``parm/wflow/verify.yaml`` file in the ``rocoto: tasks: taskgroups:`` section of ``config.yaml``.
+To use METplus verification,  MET and METplus modules need to be installed. To turn on verification tasks in the workflow, include the ``parm/wflow/verify.yaml`` file in the ``rocoto: tasks: taskgroups:`` section of ``config.yaml``.
```
Comment (MichaelLueken) [inline docs/UsersGuide/source/RunSRW.rst:683]: Should `parm/wflow/verify.yaml` be `parm/wflow/verify_pre.yaml`?

File: docs/UsersGuide/source/VXCases.rst [hunk 3]
```diff
@@ -110,21 +110,14 @@ where ``<path/to/ufs-srweather-app/ush>`` is replaced by the actual path to the
 Then, edit the configuration file (``config.yaml``) to include the variables and values in the sample configuration excerpt below (variables not listed below do not need to be changed or removed). Users must be sure to substitute values in ``<>`` with values appropriate to their system.  
 
 .. note::
-   Users working on a `Level 1 platform <https://github.com/ufs-community/ufs-srweather-app/wiki/Supported-Platforms-and-Compilers>`__ do not need to add or update the following variables: ``MET_INSTALL_DIR``, ``METPLUS_PATH``, ``MET_BIN_EXEC``, ``CCPA_OBS_DIR``, ``MRMS_OBS_DIR``, and ``NDAS_OBS_DIR``
+   Variables ``CCPA_OBS_DIR``, ``MRMS_OBS_DIR``, and ``NDAS_OBS_DIR`` are set in the ./ush/machine.yaml configuration. Variables ``MET_INSTALL_DIR``, ``METPLUS_PATH``, ``MET_BIN_EXEC`` are set in modulefiles for met/xx.x.x and metplus/x.x.x, when the modules are loaded in ./modulefiles/tasks/<platform>/run_vx.local  (run_vx.local.lua modulefile)
```
Comment (MichaelLueken) [inline docs/UsersGuide/source/VXCases.rst]: Should `./ush/machine.yaml` be `./ush/machine/*.yaml`?

**Review by MichaelLueken — COMMENTED** [review]
@natalie-perlin -

Overall, everything looks good!  I have included two comments as well (changing the workflow file from `parm/wflow/verify.yaml` to `parm/wflow/verify_pre.yaml` and differentiating between `ush/machine.yaml` and `ush/machine/*.yaml`).

I was also able to test your changes on Jet (verification only) and all five tests passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
MET_ensemble_verification                                          COMPLETE              29.81
MET_ensemble_verification_only_vx                                  COMPLETE               1.04
MET_ensemble_verification_only_vx_time_lag                         COMPLETE               4.10
MET_verification                                                   COMPLETE              17.04
MET_verification_only_vx                                           COMPLETE               0.21
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE              52.20
```

File: docs/UsersGuide/source/RunSRW.rst (hunk 2 above)
Comment (natalie-perlin) [reply docs/UsersGuide/source/RunSRW.rst:683]: It looks like it may be all the `verify_*.yaml`  files.  I'm not sure with the exact steps so far, and these are suggested preliminary documentation changes.  I've included a note that this need further correction! There are three files verify_det.yaml , view verify_pre.yaml, verify_ens.yaml, which is a change from the previously used single verify.yaml.

File: docs/UsersGuide/source/VXCases.rst (hunk 3 above)
Comment (natalie-perlin) [reply docs/UsersGuide/source/VXCases.rst]: Updated to `./ush/machine/<platform>.yaml`

**Comment by natalie-perlin** [comment]
The issue https://github.com/ufs-community/ufs-srweather-app/issues/863 will be resolved with the current PR.

File: docs/UsersGuide/source/ConfigWorkflow.rst [hunk 4]
```diff
@@ -130,15 +130,6 @@ METplus Parameters
...
    
-``MET_INSTALL_DIR``: (Default: "")
-   Path to top-level directory of MET installation.
-
-``METPLUS_PATH``: (Default: "")
-   Path to top-level directory of METplus installation.
-
-``MET_BIN_EXEC``: (Default: "")
-   Name of subdirectory where METplus executables are installed.
-
```
Comment (mkavulich) [inline docs/UsersGuide/source/ConfigWorkflow.rst:141]: I know this might be opening up a can of worms, but will the removal of these variables make it harder for people to run the app using MET on unsupported platforms?

Comment (mkavulich) [reply docs/UsersGuide/source/ConfigWorkflow.rst:141]: Or is the MET package going to be released with spack-stack? If so that would be great!

Comment (mark-a-potts) [reply docs/UsersGuide/source/ConfigWorkflow.rst:141]: Met 10.1.1 is included in spack-stack version 1.4.1.

Comment (mark-a-potts) [reply docs/UsersGuide/source/ConfigWorkflow.rst:141]: The environment variables "met_ROOT" and "MET_BASE" are set by the module for met.

**Review by MichaelLueken — APPROVED** [review]
@natalie-perlin -

Thank you very much for addressing my concerns!  Your modifications look good to me.  I will go ahead and provide my approval now.

Please note that I will be holding off on launching the automated Jenkins tests until Orion comes back up (given the additional modifications related to moving the Orion hpc-stack from role-epic-ps to role-epic).

File: docs/UsersGuide/source/ConfigWorkflow.rst (hunk 4 above)
Comment (natalie-perlin) [reply docs/UsersGuide/source/ConfigWorkflow.rst:141]: @mkavulich @mark-a-potts -
The variables `MET_INSTALL_DIR`, and `MET_BIN_EXEC` are set in the modulefile for met/10.1.2, in addition to the MET_ROOT and MET_BASE. They were added because of their extensive use throughout the scripts and code. My initial attempt was indeed to keep only `MET_ROOT` and `MET_BASE` in the modulefile, and to define MET_INSTALL_DIR and  MET_BIN_EXEC in the scripts, but this needs to be done repeatedly.  The documentation for the met also suggest use for MET_INSTALL_DIR env. variable (see e.g., https://met.readthedocs.io/en/main_v10.1/Users_Guide/plotting.html)

And `METPLUS_PATH` is set in the modulepath for the metplus/4.1.3.

**Comment by MichaelLueken** [comment]
The verification WE2E tests were run on Orion and all tests successfully passed:

```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
MET_ensemble_verification                                          COMPLETE              18.86
MET_ensemble_verification_only_vx                                  COMPLETE               0.91
MET_ensemble_verification_only_vx_time_lag                         COMPLETE               3.73
MET_verification                                                   COMPLETE               9.49
MET_verification_only_vx                                           COMPLETE               0.12
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE              33.11
```

The Cheyenne Intel WE2E coverage tests were manually run on Hera and all tests successfully passed:

```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
custom_GFDLgrid__GFDLgrid_USE_NUM_CELLS_IN_FILENAMES_eq_FALSE      COMPLETE              11.21
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot     COMPLETE              29.91
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16                COMPLETE              19.55
grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_HRRR           COMPLETE              25.42
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta    COMPLETE               8.58
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_HRRR_suite_HRRR                COMPLETE              16.47
pregen_grid_orog_sfc_climo                                         COMPLETE               7.58
specify_template_filenames                                         COMPLETE               7.31
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             126.03
```

And the Cheyenne GNU WE2E coverage tests were manually run on Hera and all tests successfully passed:

```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
grid_CONUS_25km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16      COMPLETE              20.16
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta      COMPLETE             225.99
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp  COMPLETE             109.29
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              27.27
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR             COMPLETE              36.95
grid_RRFS_CONUScompact_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16   COMPLETE              22.26
grid_RRFS_NA_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RAP                 COMPLETE             318.31
grid_SUBCONUS_Ind_3km_ics_NAM_lbcs_NAM_suite_GFS_v16               COMPLETE              49.60
specify_EXTRN_MDL_SYSBASEDIR_ICS_LBCS                              COMPLETE              10.10
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             819.93
```

Awaiting completion of Jenkins tests now.

**Comment by MichaelLueken** [comment]
@natalie-perlin -

The Hera GNU WE2E coverage test, `MET_ensemble_verification_only_vx_time_lag`, is failing in both `run_MET_GenEnsProd_vx_SFC` and `run_MET_GenEnsProd_vx_UPA` tasks due to hitting the time limit:

`slurmstepd: error: *** JOB 47745246 ON h5c52 CANCELLED AT 2023-08-04T19:30:59 DUE TO TIME LIMIT ***`

While changing from static libraries to HPC-stack modules, are you aware of any reason why these two tasks seem to now run longer for Hera GNU?  I'm seeing this for both manual and automated Jenkins testing.  Please see `/scratch1/NCEPDEV/stmp2/role.epic/jenkins/workspace/fs-srweather-app_pipeline_PR-826/expt_dirs/MET_ensemble_verification_only_vx_time_lag` for the Jenkins working directory associated with this PR.

**Comment by natalie-perlin** [comment]
@MichaelLueken - 
I'll take a look at Hera Gnu runs, haven't run it for gnu compiler. 
Hera Gnu compilers were known to be slower, but there might be another reason for the failure.

**Comment by MichaelLueken** [comment]
I was able to successfully run all verification tests on Hera GNU, with the exception of `MET_ensemble_verification_only_vx_time_lag`:

```
Experiment MET_verification_only_vx is COMPLETE
Took 0:03:35.738463; will no longer monitor.
Experiment MET_ensemble_verification_only_vx is COMPLETE
Took 0:17:49.131284; will no longer monitor.
Experiment MET_verification is COMPLETE
Took 0:26:45.456390; will no longer monitor.
Experiment MET_ensemble_verification is COMPLETE
Took 0:47:46.819661; will no longer monitor.
```

Since the rest of the tests run without issue, I'm inclined to agree that there might be an issue with the current `MET_ensemble_verification_only_vx_time_lag` test.  I'll try and dig into this as well.

**Comment by natalie-perlin** [comment]
@MichaelLueken - the issue with Hera gnu was with the installation of these older modules. All seem to be resolved after I reinstalled met/10.1.2 and metplus/4.1.3. 
Manually running met verification tests on Hera, currently 4 out of 5 finished, one more is still running:

```
Writing information for all experiments to WE2E_tests_20230807171118.yaml
Checking tests available for monitoring...
Starting experiment MET_verification running
Updating database for experiment MET_verification
Starting experiment MET_verification_only_vx running
Updating database for experiment MET_verification_only_vx
Starting experiment MET_ensemble_verification running
Updating database for experiment MET_ensemble_verification
Starting experiment MET_ensemble_verification_only_vx running
Updating database for experiment MET_ensemble_verification_only_vx
Starting experiment MET_ensemble_verification_only_vx_time_lag running
Updating database for experiment MET_ensemble_verification_only_vx_time_lag
Setup complete; monitoring 5 experiments
Use ctrl-c to pause job submission/monitoring
Experiment MET_verification_only_vx is COMPLETE
Took 0:03:45.488077; will no longer monitor.
Experiment MET_ensemble_verification_only_vx is COMPLETE
Took 0:17:49.627754; will no longer monitor.
Experiment MET_verification is COMPLETE
Took 0:29:00.411291; will no longer monitor.
Experiment MET_ensemble_verification is COMPLETE
Took 0:47:51.449840; will no longer monitor.
```
 The last test, MET_ensemble_verification_only_vx_time_lag, is still running, but all going successfully so far:
 
```
 (workflow_tools) [Natalie.Perlin@Hera:/scratch1/NCEPDEV/stmp2/Natalie.Perlin/SRW/expt_dirs/MET_ensemble_verification_only_vx_time_lag]$  rocotostat -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -v 10
       CYCLE                    TASK                       JOBID               STATE         EXIT STATUS     TRIES      DURATION
================================================================================================================================
202105050000       run_MET_Pb2nc_obs                    47836209           SUCCEEDED                   0         1          48.0
202105050000    run_MET_PcpCombine_obs_APCP01h                    47836210           SUCCEEDED                   0         1          16.0
202105050000    run_MET_PcpCombine_obs_APCP03h                    47836211           SUCCEEDED                   0         1          15.0
202105050000    run_MET_PcpCombine_obs_APCP06h                    47836212           SUCCEEDED                   0         1          14.0
202105050000    check_post_output_mem001                    47836213           SUCCEEDED                   0         1          12.0
202105050000    check_post_output_mem002                    47836214           SUCCEEDED                   0         1          11.0
202105050000    run_MET_PcpCombine_fcst_APCP01h_mem001                    47836256           SUCCEEDED                   0         1          32.0
202105050000    run_MET_PcpCombine_fcst_APCP01h_mem002                    47836257           SUCCEEDED                   0         1          31.0
202105050000    run_MET_PcpCombine_fcst_APCP03h_mem001                    47836258           SUCCEEDED                   0         1          27.0
202105050000    run_MET_PcpCombine_fcst_APCP03h_mem002                    47836259           SUCCEEDED                   0         1          27.0
202105050000    run_MET_PcpCombine_fcst_APCP06h_mem001                    47836260           SUCCEEDED                   0         1          26.0
202105050000    run_MET_PcpCombine_fcst_APCP06h_mem002                    47836261           SUCCEEDED                   0         1          26.0
202105050000    run_MET_GridStat_vx_APCP01h_mem001                    47836305           SUCCEEDED                   0         1         508.0
202105050000    run_MET_GridStat_vx_APCP01h_mem002                    47836306           SUCCEEDED                   0         1         504.0
202105050000    run_MET_GridStat_vx_APCP03h_mem001                    47836307           SUCCEEDED                   0         1         205.0
202105050000    run_MET_GridStat_vx_APCP03h_mem002                    47836308           SUCCEEDED                   0         1         204.0
202105050000    run_MET_GridStat_vx_APCP06h_mem001                    47836309           SUCCEEDED                   0         1         124.0
202105050000    run_MET_GridStat_vx_APCP06h_mem002                    47836310           SUCCEEDED                   0         1         126.0
202105050000    run_MET_GridStat_vx_REFC_mem001                    47836262           SUCCEEDED                   0         1         527.0
202105050000    run_MET_GridStat_vx_RETOP_mem001                    47836263           SUCCEEDED                   0         1         559.0
202105050000    run_MET_GridStat_vx_REFC_mem002                    47836264           SUCCEEDED                   0         1         531.0
202105050000    run_MET_GridStat_vx_RETOP_mem002                    47836265           SUCCEEDED                   0         1         557.0
202105050000    run_MET_PointStat_vx_SFC_mem001                    47836288           SUCCEEDED                   0         1         221.0
202105050000    run_MET_PointStat_vx_UPA_mem001                    47836289           SUCCEEDED                   0         1         113.0
202105050000    run_MET_PointStat_vx_SFC_mem002                    47836290           SUCCEEDED                   0         1         225.0
202105050000    run_MET_PointStat_vx_UPA_mem002                    47836291           SUCCEEDED                   0         1         113.0
202105050000    run_MET_GenEnsProd_vx_APCP01h                    47836311           SUCCEEDED                   0         1        1210.0
202105050000    run_MET_EnsembleStat_vx_APCP01h                    47836654           SUCCEEDED                   0         1        1321.0
202105050000    run_MET_GenEnsProd_vx_APCP03h                    47836312           SUCCEEDED                   0         1         399.0
202105050000    run_MET_EnsembleStat_vx_APCP03h                    47836392           SUCCEEDED                   0         1         449.0
202105050000    run_MET_GenEnsProd_vx_APCP06h                    47836313           SUCCEEDED                   0         1         205.0
202105050000    run_MET_EnsembleStat_vx_APCP06h                    47836363           SUCCEEDED                   0         1         225.0
202105050000    run_MET_GenEnsProd_vx_REFC                    47836224           SUCCEEDED                   0         1        1404.0
202105050000    run_MET_EnsembleStat_vx_REFC                    47836703           SUCCEEDED                   0         1         444.0
202105050000    run_MET_GenEnsProd_vx_RETOP                    47836225           SUCCEEDED                   0         1        1407.0
202105050000    run_MET_EnsembleStat_vx_RETOP                    47836705           SUCCEEDED                   0         1         513.0
202105050000    run_MET_GenEnsProd_vx_SFC                    47838115             RUNNING                   -         1           0.0
202105050000    run_MET_EnsembleStat_vx_SFC                           -                   -                   -         -             -
202105050000    run_MET_GenEnsProd_vx_UPA                    47838116             RUNNING                   -         1           0.0
202105050000    run_MET_EnsembleStat_vx_UPA                           -                   -                   -         -             -
202105050000    run_MET_GridStat_vx_ensmean_APCP01h                    47836655           SUCCEEDED                   0         1         447.0
202105050000    run_MET_GridStat_vx_ensmean_APCP03h                    47836393           SUCCEEDED                   0         1         151.0
202105050000    run_MET_GridStat_vx_ensmean_APCP06h                    47836364           SUCCEEDED                   0         1          79.0
202105050000    run_MET_GridStat_vx_ensprob_APCP01h                    47836656           SUCCEEDED                   0         1         902.0
202105050000    run_MET_GridStat_vx_ensprob_APCP03h                    47836394           SUCCEEDED                   0         1         300.0
202105050000    run_MET_GridStat_vx_ensprob_APCP06h                    47836365           SUCCEEDED                   0         1         155.0
```

On Cheyenne, the previous installations of met and metplus for Gnu compilers were fully complete for met/11.02 and metplus/5.0.2; thus I reinstalled  met/10.1.2 and metplus/4.1.3 for Cheyenne Gnu:
```
/glade/work/epicufsrt/contrib/hpc-stack/gnu10.1.0
/glade/work/epicufsrt/contrib/hpc-stack/gnu11.2.0
```
Tests cannot be run though due to account overspent. Please feel free to test it if needed.

**Comment by MichaelLueken** [comment]
@natalie-perlin -

I'm resubmitting the `MET_ensemble_verification_only_vx_time_lag` test now.

Please let me know if you the two tasks that were still running for your test - `run_MET_GenEnsProd_vx_SFC` and `run_MET_GenEnsProd_vx_UPA` - successfully passed.  These are the two tasks that seem to time out after an hour.

**Comment by natalie-perlin** [comment]
@MichaelLueken - yes, indeed these two tasks timed out, even though they seemed to be running OK as appears from the log files. 

I'm resubmitting these tasks and increasing the time to 2:00:00 from the original 1:00:00, modifying them directly in FV3LAM_wflow.xml.

Some comparisons of similar tasks for the runs with intel compiler vs. runs with gnu compiler indeed show a significant time increase, 2-fold and 4+-fold,. Notice for example, tasks run_MET_GenEnsProd_vx_REFC, run_MET_EnsembleStat_vx_REFC, run_MET_GenEnsProd_vx_RETOP, run_MET_EnsembleStat_vx_RETOP:

`Hera with Intel` compiler:
```
202105050000    run_MET_GenEnsProd_vx_REFC                    47607444           SUCCEEDED                   0         1         309.0
202105050000    run_MET_EnsembleStat_vx_REFC                    47607576           SUCCEEDED                   0         1         258.0
202105050000    run_MET_GenEnsProd_vx_RETOP                    47607445           SUCCEEDED                   0         1         305.0
202105050000    run_MET_EnsembleStat_vx_RETOP                    47607570           SUCCEEDED                   0         1         276.0
```

`Hera with gnu/9.2` compiler:

```
202105050000    run_MET_GenEnsProd_vx_REFC                    47836224           SUCCEEDED                   0         1        1404.0
202105050000    run_MET_EnsembleStat_vx_REFC                    47836703           SUCCEEDED                   0         1         444.0
202105050000    run_MET_GenEnsProd_vx_RETOP                    47836225           SUCCEEDED                   0         1        1407.0
202105050000    run_MET_EnsembleStat_vx_RETOP                    47836705           SUCCEEDED                   0         1         513.0
```

**Comment by natalie-perlin** [comment]
The tasks run_MET_GenEnsProd_vx_SFC and run_MET_GenEnsProd_vx_UPA had the following runtimes for the Hera Intel compilers:
```
202105050000    run_MET_GenEnsProd_vx_SFC                    47607490           SUCCEEDED                   0         1        1571.0
202105050000    run_MET_GenEnsProd_vx_UPA                    47607491           SUCCEEDED                   0         1         778.0

```
Anticipating possible 4-fold increase, we'd need to have ~6300 s, i.e. 1.75 hours, or for 4.6-fold increase, slightly over 7200 s (2hours).

**Comment by natalie-perlin** [comment]
@MichaelLueken -
 All the verification tasks were eventually completed on Hera Gnu, but it took over 2 hours (7945s) for the longest task run_MET_GenEnsProd_vx_SFC. Time requests for the task needed to be adjusted.
 
```
 202105050000    run_MET_GenEnsProd_vx_SFC                    47855057           SUCCEEDED                   0         1        7945.0
202105050000    run_MET_EnsembleStat_vx_SFC                    47869213           SUCCEEDED                   0         1         369.0
202105050000    run_MET_GenEnsProd_vx_UPA                    47839775           SUCCEEDED                   0         1        3907.0
202105050000    run_MET_EnsembleStat_vx_UPA                    47846555           SUCCEEDED                   0         1         148.0

```
 How we should proceed with this?

**Comment by natalie-perlin** [comment]
@mkavulich -
what would be a good way to specify longer walltime as task requirement for the met verification tasks?..

The tasks  run_MET_GenEnsProd_vx_SFC  and run_MET_GenEnsProd_vx_UPA  running on Hera gnu/9.2 take way over a default hour of walltime.
I was looking through the documentation on Workflow https://ufs-srweather-app.readthedocs.io/en/develop/ConfigWorkflow.html
 or  WE2E tests https://ufs-srweather-app.readthedocs.io/en/develop/WE2Etests.html   to look for the clues on walltime setup. (Please feel free to point to the right section in the docs if any!)

**Comment by MichaelLueken** [comment]
@natalie-perlin -

It looks like going into `parm/wflow/verify_ens.yaml`, going to line 140, and adding:

`walltime: 02:30:00`

will increase the walltime for the `run_MET_GenEnsProd_vx_UPA/SFC` tasks to two and a half hours.  Please note that this value can be changed as desired.

The final section would look like:

```
metatask_GenEnsProd_EnsembleStat_NDAS:
  var:
    VAR: '{% for var in verification.VX_FIELDS %}{% if var in ["SFC", "UPA"] %}{{ "%s " % var }}{% endif %}{% endfor %}'
  task_run_MET_GenEnsProd_vx_#VAR#: &task_GenEnsProd_NDAS
    <<: *default_task_verify_ens
    command: '&LOAD_MODULES_RUN_TASK_FP; "run_vx" "&JOBSdir;/JREGIONAL_RUN_MET_GENENSPROD_OR_ENSEMBLESTAT"'
    envars: &envars_GenEnsProd_NDAS
      <<: *default_vars
      OBS_DIR: '&NDAS_OBS_DIR;'
      VAR: '#VAR#'
      MET_TOOL: 'GENENSPROD'
      OBTYPE: 'NDAS'
      ACCUM_HH: '01'
    walltime: 02:30:00
    dependency:
```
Additionally, you will need to add the following to line 156:

`walltime: 01:00:00`

Otherwise, the updated walltime will be used in the `run_MET_EnsembleStat_vx_UPA/SFC` section as well.  The final appearance here should look like:

```
  task_run_MET_EnsembleStat_vx_#VAR#:
    <<: *task_GenEnsProd_NDAS
    envars:
      <<: *envars_GenEnsProd_NDAS
      MET_TOOL: 'ENSEMBLESTAT'
    walltime: 01:00:00
    dependency:
```
Please see `/scratch2/NAGAPE/epic/Michael.Lueken/ufs-srweather-app/parm/wflow/verify_ens.yaml` for what the modified file should look like.

Please note that I'm still in the process of testing these changes, so I would recommend running the test with the modified `parm/wflow/verify_ens.yaml` file before committing it and pushing back.  I have been able to verify that the two tests that need a longer walltime will have it, while other tasks will not have the extended walltimes.

**Comment by MichaelLueken** [comment]
@natalie-perlin -

My test has successfully completed:

```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
MET_ensemble_verification_only_vx_time_lag                         COMPLETE               8.55
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE               8.55
```
The two tasks that were failing are now passing with the increased walltime from `parm/wflow/verify_ens.yaml`:
```
202105050000    run_MET_GenEnsProd_vx_SFC                    47872102           SUCCEEDED                   0         1        7922.0
202105050000    run_MET_EnsembleStat_vx_SFC                    47878288           SUCCEEDED                   0         1         363.0
202105050000    run_MET_GenEnsProd_vx_UPA                    47872103           SUCCEEDED                   0         1        3838.0
202105050000    run_MET_EnsembleStat_vx_UPA                    47875308           SUCCEEDED                   0         1         147.0
```
Once you have verified that the modification works, please commit the change, push it to your branch, then I will relaunch the Hera Jenkins tests.

**Comment by natalie-perlin** [comment]
Implemented recent changes in develop into my branch, added the changes for the ./parm/wflow/parm/wflow/verify_ens.yaml. The workflow generated FV3LAM_wflow.xml with "wallclock 2:30" correctly, and I'm waiting for the test to finish.

**Comment by MichaelLueken** [comment]
The Hera GNU WE2E coverage tests have been manually run and all tests have successfully passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2019061200         COMPLETE              18.69
get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS                             COMPLETE              45.32
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR             COMPLETE             230.44
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp  COMPLETE              17.64
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta      COMPLETE              35.98
quilting_false                                                     COMPLETE              13.69
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0              COMPLETE              22.77
GST_release_public_v1                                              COMPLETE              54.02
MET_verification_only_vx                                           COMPLETE               0.13
MET_ensemble_verification_only_vx_time_lag                         COMPLETE               8.55
nco_grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16      COMPLETE             334.74
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             781.97
```
Will requeue the automated tests on Hera to make sure they pass now as well.

**Comment by natalie-perlin** [comment]
All the tasks succeeded using the updated branch:
```
202105050000    run_MET_GenEnsProd_vx_SFC                    47885737           SUCCEEDED                   0         1        7839.0
202105050000    run_MET_EnsembleStat_vx_SFC                    47894358           SUCCEEDED                   0         1         370.0
202105050000    run_MET_GenEnsProd_vx_UPA                    47885738           SUCCEEDED                   0         1        3855.0
202105050000    run_MET_EnsembleStat_vx_UPA                    47890632           SUCCEEDED                   0         1         147.0
```

So if no more questions, I guess this PR is ready to be merged.

**Comment by MichaelLueken** [comment]
The automated Jenkins tests on Hera successfully passed GNU:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2019061200         COMPLETE              19.32
get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS                             COMPLETE              44.11
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR             COMPLETE             231.61
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp  COMPLETE              17.81
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta      COMPLETE              35.96
quilting_false                                                     COMPLETE              13.79
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0              COMPLETE              23.23
GST_release_public_v1                                              COMPLETE              54.28
MET_verification_only_vx                                           COMPLETE               0.14
MET_ensemble_verification_only_vx_time_lag                         COMPLETE               8.56
nco_grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16      COMPLETE             337.93
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             786.74
```
and Intel:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2019061200          COMPLETE               6.10
get_from_HPSS_ics_GDAS_lbcs_GDAS_fmt_netcdf_2022040400_ensemble_2  COMPLETE             774.63
get_from_HPSS_ics_HRRR_lbcs_RAP                                    COMPLETE              14.25
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp  COMPLETE               8.59
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2        COMPLETE               6.08
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16          COMPLETE              11.43
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_RAP                 COMPLETE              10.62
grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2        COMPLETE               6.84
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2         COMPLETE             250.73
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16           COMPLETE             312.12
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_HRRR            COMPLETE             335.11
pregen_grid_orog_sfc_climo                                         COMPLETE               7.37
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            1743.87
```
Moving forward with merging this work now.

**Comment by natalie-perlin** [comment]
@gsketefian - 
  I'm looking to understand a little better on what does met and meplus modules use as to file formats and binaries needed to be built to read these files. 
  There are some problems with using MET/metplus modules being build on Derecho Cray platform, which is set differently from other Crays, such as Gaea C5 and Gaea C5. Errors appear at the runtime, and resemble similar errors we've seen before on Derecho that were resolved by more differential use of serial vs mpi compilers. 
  
  The binaries that returns error are from **./met/10.1.2/bin/**, and are grid_stat, pb2nc, pcp_combine (maybe more), so this must be something to deal with the netcdf files.
  One of the tasks from the Met_verification experiment, get_obs_ccpa, looks for grib2 files and uses the ones staged on disk  (/glade/work/epicufsrt/contrib/UFS_SRW_data/develop/obs_data/ccpa/proc/20190615/ccpa.t06z.01h.hrap.conus.gb2 on Cheyenne/Derecho). Which means that it uses grib2 files. This implies I may need to look into the way wgrib2 module/binaries are built on the system.
  Does it seem reasonable that netcdf and grib2 files are the only formats used (and that may require more scrutiny)?

**Comment by gsketefian** [comment]
@natalie-perlin As far as I know, in the SRW App the vx that MET/METplus does uses grib2, netcdf, and text formats.  But I'm not an expert on METplus inner workings.  

What installation of MET/METplus on Derecho are you using?  If it wasn't installed by someone on the METplus team, it might be worthwhile to contact them.  They'll have more insight than me.  I think Julie Prestopnik is usually the one who does installations.
